WIP: add debian packaging
RobotLocomotion/drake-ci pull request #157
Opened 2022-05-12 20:15 UTC by svenevs

Toward https://github.com/RobotLocomotion/drake/issues/17177.

2022-05-12 20:37 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`driver/configurations/bazel/step-create-package-debian.cmake` line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N1tz9171UG5VN3vTtqo:-N1tz9171UG5VN3vTtqp:bkwungx) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/fcb639269e108c69c72049093becfe6cf36478c0/driver/configurations/bazel/step-create-package-debian.cmake#L40)):*
> ```CMake
>   notice("CTest Status: CREATING PACKAGE DEBIAN")
>   # NOTE: do not use DASHBOARD_BAZEL_*_OPTIONS with this script.
>   set(DEBIAN_ARGS "run /tools/release_engineering/dev:repack_deb -- --tgz ${DASHBOARD_WORKSPACE}/${DASHBOARD_PACKAGE_ARCHIVE_NAME} --output-dir ${DASHBOARD_WORKSPACE}")
> ```

TODO: don't merge this until `//tools/release_engineering/dev:repack_deb` => `/tools/release_engineering:repack_deb`


<!-- Sent from Reviewable.io -->

2022-05-16 19:01 UTC, svenevs reviewed
+@mwoehlke-kitware for review please.  This is ready to have its code reviewed, but remains `blocked` until the `repack_deb` file goes under platform review to avoid committing a `dev/` path to this repo.

The PR description also links some jobs that included a "fake" nightly to confirm that files still get uploaded, it relies on `DASHBOARD_DEBIAN_ARCHIVE_TOTAL_UPLOADS` being equal to 2 (which is configured by the existing `.tar.gz` uploads).  We won't be able to confirm it goes to the right place until we actually start running the nightlies, but the `DASHBOARD_TRACK` variable will control its destination.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-:-N2DCqkPCSFmL1tDox9B:b-ig7wqn)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @mwoehlke-kitware)

___
*[`driver/platform.cmake` line 96 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DCzJI8NmsXBjbh04X:-N2DCzJI8NmsXBjbh04Y:b-ybrl9) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/platform.cmake#L96)):*
> ```CMake
>     set(PROVISION_ARGS "--without-test-only")
>   elseif(PACKAGE)
>     set(PROVISION_ARGS "--without-test-only --with-maintainer-only")
> ```

FYI the linked `mac-monterey-unprovisioned-clang-cmake-experimental-release` and `linux-focal-unprovisioned-gcc-cmake-experimental-everything-release` jobs in the main PR description here are to test that `GENERATOR STREQUAL "cmake"` still installs as expected.

The successful `linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging` confirm that `alien` and `fakeroot` get installed via `--with-maintainer-only`.
___
*[`driver/configurations/bazel/step-upload-debian-archive.cmake` line 49 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DDh8Z1MYlY-Qsfwa0:-N2DDh8Z1MYlY-Qsfwa1:bbx6y2e) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-upload-debian-archive.cmake#L49)):*
> ```CMake
>   set(DASHBOARD_DEBIAN_ARCHIVE_STORAGE_CLASS "${DASHBOARD_PACKAGE_ARCHIVE_STORAGE_CLASS}")
>   set(DASHBOARD_DEBIAN_ARCHIVE_FOLDER "${DASHBOARD_PACKAGE_ARCHIVE_FOLDER}")
>   set(DASHBOARD_DEBIAN_ARCHIVE_DISTRIBUTION "${DASHBOARD_PACKAGE_ARCHIVE_DISTRIBUTION}")
> ```

See `step-upload-package-archive.cmake` for how they are set, main thing of interest is that the cache age is different for experimental vs nightly.  I decided to shadow the variables so that I could search for `_PACKAGE_` and confirm that my original copy-paste-implementation did not overlook anything important.  Is there a reason not to do this or maybe is there something better to say in the comment other than "I was error checking my copy-pasting"?  Heh.


<!-- Sent from Reviewable.io -->

2022-05-16 19:11 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @mwoehlke-kitware)

___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DGxQvEGvD2PyZY_P2:-N2DGxQwCiTWu0DjyOfz:b-1n1fuo) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L47)):*
> ```CMake
> 
>   # https://bazel.build/blog/2016/01/27/continuous-integration.html
>   if(DEBIAN_RESULT_VARIABLE EQUAL 1)
> ```

Helpful to know where this came from: https://github.com/RobotLocomotion/drake-ci/blob/8d513f8331c4b84b352621a364a3828636f702b4/driver/configurations/bazel/step-build.cmake#L83-L110

But I only check for a subset since we aren't running `bazel build` or `bazel test`.

Did I omit any error codes that should have been included here?


<!-- Sent from Reviewable.io -->

2022-05-16 19:28 UTC, mwoehlke-kitware requested changes
Comments from a partial review, mostly streamlining suggestions... Seems okay overall, but my eyes started glazing over at the wall of S3 stuff :upside_down_face:. (Also, I suspect I don't understand S3 enough to be able to answer some of the questions there.)

> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-:-N2DKKjQCDOLixkzBYjR:b-qxn0ri)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`driver/configurations/bazel/step-upload-debian-archive.cmake` line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DJhr680sWKH9Ea7_I:-N2DJhr680sWKH9Ea7_J:b-ml1h0m) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-upload-debian-archive.cmake#L44)):*
> ```CMake
>   # set "mirror" variables here specific to the debian result.  The nightly and
>   # experimental .deb uploads are to be sibling files to the .tar.gz archive
>   # they correspond to on drake-packages (not to be uploaded to drake-apt).
> ```

...because it took me several tries to parse this sentence as currently written:



_Suggestion:_
```CMake
to which they correspond
```
___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 37 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DH2U14_XwpRJZ9zXJ:-N2DH2U20n3kvJenulj6:b-w2956q) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L37)):*
> ```CMake
> if(DASHBOARD_FAILURE OR DASHBOARD_UNSTABLE)
>   notice("CTest Status: NOT CREATING DEBIAN ARCHIVE BECAUSE BAZEL BUILD WAS NOT SUCCESSFUL")
> else()
> ```

FYI, maybe leave this as-is for now, but we might want to consider replacing these `if(FAILED)\nnotice(...)\nelse()` with `if(FAILED)\nnotice(...)\nreturn()\nendif()`, so as to not need to indent the entirety of the logic.
___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DHe3E5_oPKV25r9mh:-N2DHe3E5_oPKV25r9mi:b-kgl5a6) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L40)):*
> ```CMake
>   notice("CTest Status: CREATING DEBIAN ARCHIVE")
>   # NOTE: do not use DASHBOARD_BAZEL_*_OPTIONS with this script.
>   set(DEBIAN_ARGS "run //tools/release_engineering/dev:repack_deb -- --tgz ${DASHBOARD_WORKSPACE}/${DASHBOARD_PACKAGE_ARCHIVE_NAME} --output-dir ${DASHBOARD_WORKSPACE}")
> ```

Why can't this just be set as a list up front? `set(DEBIAN_ARGS "run" "//tools/release_engineering/dev:repack_deb" "--" ...)`?
___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DGxQvEGvD2PyZY_P2:-N2DIInF82wjODoNBg2r:b-yi8w40) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L47)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Helpful to know where this came from: https://github.com/RobotLocomotion/drake-ci/blob/8d513f8331c4b84b352621a364a3828636f702b4/driver/configurations/bazel/step-build.cmake#L83-L110

But I only check for a subset since we aren't running `bazel build` or `bazel test`.

Did I omit any error codes that should have been included here?
</blockquote></details>

Does `bazel run` even return the same things? Do we really need to care about *what* non-zero exit occurred? (We don't for example when building wheels. If this is truly valuable in many places, maybe it should be made into a function?)
___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 66 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DJAYhD191uFxKonQq:-N2DJAYhD191uFxKonQr:b-8v68q7) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L66)):*
> ```CMake
>     # Find the output debian file, its output name will differ depending on the
>     # contents of VERSION.txt from step-create-package-archive.
>     file(GLOB DEBIAN_ARCHIVE "${DASHBOARD_WORKSPACE}/*.deb")
> ```

Maybe `step-create-package-archive` should export this, if it doesn't already? (It can't be derived from `DASHBOARD_PACKAGE_NAME`?)


<!-- Sent from Reviewable.io -->

2022-06-01 20:52 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @mwoehlke-kitware)

___
*[`driver/configurations/bazel/step-upload-debian-archive.cmake` line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DJhr680sWKH9Ea7_I:-N3W1CwHA6mLs9LiVK4w:b-lj09z2) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-upload-debian-archive.cmake#L44)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

...because it took me several tries to parse this sentence as currently written:
</blockquote></details>

Done, sentence is coherent now.
___
*[`driver/configurations/bazel/step-upload-debian-archive.cmake` line 49 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DDh8Z1MYlY-Qsfwa0:-N3W04br20wnDKpgqYN5:b-dcwwf7) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-upload-debian-archive.cmake#L49)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

See `step-upload-package-archive.cmake` for how they are set, main thing of interest is that the cache age is different for experimental vs nightly.  I decided to shadow the variables so that I could search for `_PACKAGE_` and confirm that my original copy-paste-implementation did not overlook anything important.  Is there a reason not to do this or maybe is there something better to say in the comment other than "I was error checking my copy-pasting"?  Heh.
</blockquote></details>

Done, I'm fine with shadowing it makes things clearer IMO and gives us the ability to change in the future if desired.
___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 37 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DH2U14_XwpRJZ9zXJ:-N3W1GBA2ifReeUEeD9g:b-i9jlzd) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L37)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

FYI, maybe leave this as-is for now, but we might want to consider replacing these `if(FAILED)\nnotice(...)\nelse()` with `if(FAILED)\nnotice(...)\nreturn()\nendif()`, so as to not need to indent the entirety of the logic.
</blockquote></details>

Ok, yeah supposedly a lot of this is going to get overhauled for python.  I'd rather leave it as is for consistency with everything else.
___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DHe3E5_oPKV25r9mh:-N3Vt2FL3-kqQU8D8IDu:b-ohdo8) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L40)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Why can't this just be set as a list up front? `set(DEBIAN_ARGS "run" "//tools/release_engineering/dev:repack_deb" "--" ...)`?
</blockquote></details>

Done, good call.
___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DGxQvEGvD2PyZY_P2:-N3VtPqOCrDAIf4dl4b_:b-phsqkw) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L47)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Does `bazel run` even return the same things? Do we really need to care about *what* non-zero exit occurred? (We don't for example when building wheels. If this is truly valuable in many places, maybe it should be made into a function?)
</blockquote></details>

OK, made it just check for non-zero exit code to fail.
___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 66 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DJAYhD191uFxKonQq:-N3VuMNw0QvwgrQ5zS-W:brje89e) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L66)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Maybe `step-create-package-archive` should export this, if it doesn't already? (It can't be derived from `DASHBOARD_PACKAGE_NAME`?)
</blockquote></details>

I added what it should be and a `NOTE`, I think this will work for now -- going to add a test job.


<!-- Sent from Reviewable.io -->

2022-06-01 20:54 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @mwoehlke-kitware)

___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 66 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DJAYhD191uFxKonQq:-N3W1yv_BnTotzd85t4k:buoqmo8) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L66)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

I added what it should be and a `NOTE`, I think this will work for now -- going to add a test job.
</blockquote></details>

https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/13/


<!-- Sent from Reviewable.io -->

2022-06-02 15:14 UTC, mwoehlke-kitware reviewed
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`driver/configurations/bazel/step-upload-debian-archive.cmake` line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DJhr680sWKH9Ea7_I:-N3Zyh6k6Lj5PSwT2Qb2:b-gopryv) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-upload-debian-archive.cmake#L44)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Done, sentence is coherent now.
</blockquote></details>

Apparently, that sentence no longer exists :slightly_smiling_face:.
___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 40 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N3Zxcxe3jbmH6JmtA5P:-N3Zxcxf5-Eea4mCxA0H:b-73tcbx) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/0b3e62d1503aab44467b866483c033302781fae0/driver/configurations/bazel/step-create-debian-archive.cmake#L40)):*
> ```CMake
>   notice("CTest Status: CREATING DEBIAN ARCHIVE")
>   # NOTE: do not use DASHBOARD_BAZEL_*_OPTIONS with this script.
>   set(DEBIAN_ARGS_LIST
> ```

Huh. Apparently, use of `separate_arguments` is a lot more pervasive than I was aware. In any case, `_LIST` seems to only be used with that pattern. Elsewhere where we don't use `separate_arguments`, the variable is just `_ARGS`.


<!-- Sent from Reviewable.io -->

2022-06-02 16:52 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 66 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DJAYhD191uFxKonQq:-N3_K30L6Oln2YtrZnmT:b-vhw6j3) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L66)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/13/
</blockquote></details>

Working, was cleaning up the packaging script

https://github.com/RobotLocomotion/drake/blob/e80d001876a8c14dbd46e8a5f8c0d1eaf0e7de1a/tools/release_engineering/dev/repack_deb.py#L107-L109

this is going to break on the nightlies.  This is why I previously kind of just rage-quit and globbed for `*.deb` and assert that there is only 1.  Green light to restore that?


<!-- Sent from Reviewable.io -->

2022-06-02 16:55 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 66 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DJAYhD191uFxKonQq:-N3_Kslw9ndAmnXQiDCp:bhxrj3n) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L66)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, was cleaning up the packaging script

https://github.com/RobotLocomotion/drake/blob/e80d001876a8c14dbd46e8a5f8c0d1eaf0e7de1a/tools/release_engineering/dev/repack_deb.py#L107-L109

this is going to break on the nightlies.  This is why I previously kind of just rage-quit and globbed for `*.deb` and assert that there is only 1.  Green light to restore that?
</blockquote></details>

Wait, sorry, that's the alien subdirectory where it builds the `.deb`, not the output filename.  I will run additional packaging tests with the current code once we are in a place to promote the script.  Sorry for the noise!


<!-- Sent from Reviewable.io -->

2022-06-09 15:51 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 66 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DJAYhD191uFxKonQq:-N489SaKCPhOdOqzRnTC:b-duf9ka) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L66)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Wait, sorry, that's the alien subdirectory where it builds the `.deb`, not the output filename.  I will run additional packaging tests with the current code once we are in a place to promote the script.  Sorry for the noise!
</blockquote></details>

Working, after drake PR merges to test this I will need to cheat and make it think it's a nightly job.
___
*[`driver/configurations/bazel/step-create-package-debian.cmake` line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N1tz9171UG5VN3vTtqo:-N489ENx395TrjyiruXx:b-uoje85) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/fcb639269e108c69c72049093becfe6cf36478c0/driver/configurations/bazel/step-create-package-debian.cmake#L40)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

TODO: don't merge this until `//tools/release_engineering/dev:repack_deb` => `/tools/release_engineering:repack_deb`
</blockquote></details>

Done, PR still blocked until it merges in drake.


<!-- Sent from Reviewable.io -->

2022-06-17 21:27 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 49 at r6](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N4nYr-t6hwLFgkwKKcc:-N4nYr-t6hwLFgkwKKcd:b-jnzcov) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b9926c9e163e65741a545c7308bc881cf4e919b1/driver/configurations/bazel/step-create-debian-archive.cmake#L49)):*
> ```CMake
>   # able to save YYYYMMDD only (without the time).
>   # if(DASHBOARD_TRACK STREQUAL "Nightly")
>   if(TRUE)  # TODO(svenevs): testing fake nightly build
> ```

Working, launched https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/23/ to confirm this is going to give us the desired output with just YYYYMMDD.  AWS python script will fail, fix next week.


<!-- Sent from Reviewable.io -->

2022-06-20 22:26 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 73 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N52-IVJ7AMPAufSHCj6:-N52BzFeAxc0Rf4Cy9PP:b-n6bjep) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cb7996a8bb1878e0d5205372d4025249151e7d1d/driver/configurations/bazel/step-create-debian-archive.cmake#L73)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, fake nightly build which should produce a `latest` here: https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/24/
</blockquote></details>

had a typo on the cmake side, injected more fake nightly stuff to force a `-latest` archive for testing the regular expression

https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/25/


<!-- Sent from Reviewable.io -->

2022-06-21 16:17 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 73 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N52-IVJ7AMPAufSHCj6:-N561qssBTkqnCKPQ5tb:b-6h07p2) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cb7996a8bb1878e0d5205372d4025249151e7d1d/driver/configurations/bazel/step-create-debian-archive.cmake#L73)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

had a typo on the cmake side, injected more fake nightly stuff to force a `-latest` archive for testing the regular expression

https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/25/
</blockquote></details>

fake "nightly" latest uploads confirm regex works as expected, we get

- https://drake-packages.csail.mit.edu/drake/experimental/drake-dev_0.0.20220620-1_amd64-focal.deb
- https://drake-packages.csail.mit.edu/drake/experimental/drake-latest-1_amd64-focal.deb

rebasing and rerunning as regular for final pass before resolving this thread


<!-- Sent from Reviewable.io -->

2022-06-21 16:29 UTC, svenevs reviewed
> Reviewed 1 of 3 files at r6, 1 of 3 files at r7, 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 73 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N52-IVJ7AMPAufSHCj6:-N564zCq76TFCMr6r2I6:b-s681va) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cb7996a8bb1878e0d5205372d4025249151e7d1d/driver/configurations/bazel/step-create-debian-archive.cmake#L73)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

fake "nightly" latest uploads confirm regex works as expected, we get

- https://drake-packages.csail.mit.edu/drake/experimental/drake-dev_0.0.20220620-1_amd64-focal.deb
- https://drake-packages.csail.mit.edu/drake/experimental/drake-latest-1_amd64-focal.deb

rebasing and rerunning as regular for final pass before resolving this thread
</blockquote></details>

experimental build: https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/26/


<!-- Sent from Reviewable.io -->

2022-06-21 17:51 UTC, mwoehlke-kitware commented
*[`tools/upload-to-aws.py` line 174 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56NTYTE4UgzdK9s3ti:-N56NTYTE4UgzdK9s3tj:bjo54ni) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L174)):*
> ```Python
>         # Wheel:
>         #   drake-0.0.YYYY.M.D.h.m.s+git<commit>-cp38-cp38-manylinux_2_31_x86_64.whl
>         #   drake-0.0.YYYY.M.D.h.m.s+git<commit>-cp39-cp39-macosx_11_0_x86_64.whl
> ```

Since this is otherwise over recommended line length:



_Suggestion:_
```Python
drake-0.0.YYYY.M.D.h.m.s+git<commit>-cp38-cp38-<platform>.whl
```


<!-- Sent from Reviewable.io -->

2022-06-21 21:38 UTC, svenevs reviewed
> Reviewed 2 of 4 files at r2, 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/upload-to-aws.py` line 174 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56NTYTE4UgzdK9s3ti:-N57BXdr-QQ9Y9gQ0phT:b-iwmn48) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L174)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Since this is otherwise over recommended line length:
</blockquote></details>

Done.  Interestingly `flake8` didn't even whine about it, I guess because there were no spaces.  BTW we may want to create a GH action on this repo to start validating `flake8`?  That's how I found `tempfile` import being removed above.
___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N2DHe3E5_oPKV25r9mh:-N57Awov3iImhA6CmILz:b-mcdgj9) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cf7c8cf17eddac2c17e4cc29d3e817894282255c/driver/configurations/bazel/step-create-debian-archive.cmake#L40)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Done, good call.
</blockquote></details>

OK, this can be resolved right?
___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 73 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N52-IVJ7AMPAufSHCj6:-N57AqsoE7fEd66MmAkp:b-fmdnwn) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cb7996a8bb1878e0d5205372d4025249151e7d1d/driver/configurations/bazel/step-create-debian-archive.cmake#L73)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

experimental build: https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/26/
</blockquote></details>

OK works as we want it to for experimental as well: `drake-dev_0.0.20220621164557-f6ed41554d3cd821c8c5c48545c508adad8d36ab-1_amd64-focal.deb`


<!-- Sent from Reviewable.io -->

2022-06-21 21:41 UTC, jwnimmer-tri commented
*[`tools/upload-to-aws.py` line 174 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56NTYTE4UgzdK9s3ti:-N57C8T32EbG0wfBLzRY:bysldnr) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L174)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Done.  Interestingly `flake8` didn't even whine about it, I guess because there were no spaces.  BTW we may want to create a GH action on this repo to start validating `flake8`?  That's how I found `tempfile` import being removed above.
</blockquote></details>

The point where this script is complicated enough to need linting is the point where it needs to move into drake.git, and the CI scripts just do `bazel run //path/to:uploader`.  Complexity belongs in Drake, not Drake-CI.  The Drake-CI layer should only ever be a simple transmogrification from Jenkins job names into setup script commands (install prereqs) and/or bazel commands, along with any injected credentials.


<!-- Sent from Reviewable.io -->

2022-06-21 21:46 UTC, svenevs reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/upload-to-aws.py` line 174 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56NTYTE4UgzdK9s3ti:-N57D8Oe-m8Z470x-Sd7:b-98zeq1) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L174)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The point where this script is complicated enough to need linting is the point where it needs to move into drake.git, and the CI scripts just do `bazel run //path/to:uploader`.  Complexity belongs in Drake, not Drake-CI.  The Drake-CI layer should only ever be a simple transmogrification from Jenkins job names into setup script commands (install prereqs) and/or bazel commands, along with any injected credentials.
</blockquote></details>

Ok, I don't think the script is there in terms of complexity.  I just ran it as a cleanliness thing.  This is the first `.py` script added here, and long term I was under the impression more would come https://github.com/RobotLocomotion/drake/issues/17177#issuecomment-1126226295

Linting checks aren't needed here though :+1:


<!-- Sent from Reviewable.io -->

2022-06-22 20:02 UTC, mwoehlke-kitware requested changes
Still haven't waded through the CMake code, though what's left looks like it won't be too bad (Reviewable breaking it up with comments isn't helping, though).

> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-:-N5Bzcyy9ioXZxk453Nv:bczjli1)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/upload-to-aws.py` line 167 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N52-S_z1oMthiDl7WbO:-N56O6f2DXlJ0hng5xUn:b-w1tcty) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cb7996a8bb1878e0d5205372d4025249151e7d1d/tools/upload-to-aws.py#L167)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI we only want `-latest` for nightly (changed `if` above to enter here), and if it cannot be discovered we want the build to be labelled as failed (in the event our regex is not working)
</blockquote></details>

The first half of your comment seems to be outdated?
___
*[`tools/upload-to-aws.py` line 170 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56LP9q1hUadduf5_Jw:-N56LP9r8tX3_1Wz0vsB:b-5ntdcg) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L170)):*
> ```Python
>         #   drake-<YYYYMMDDHHMMSS>-<hash>-<codename>.tar.gz
>         # Deb:
>         #   drake-dev_0.0.<YYYYMMDD>-1_amd64-<codename>.deb (nightly)
> ```

IIUC, this will turn into `drake-latest-1_amd64-<codename>.deb` with no `dev_`; is that okay?
___
*[`tools/upload-to-aws.py` line 193 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56LcFU97SjUNS5ABXm:-N56LcFU97SjUNS5ABXn:b32nogy) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L193)):*
> ```Python
>             raise RuntimeError(
>                 f'Failed to transform version in artifact {name}; no '
>                 '\'latest\' will be uploaded.')
> ```

I don't think we need to aggressively wrap as late as possible; breaking after the `;` instead is prettier. Although, with this being promoted to an error, I don't think we need everything after the `;` anyway.



_Suggestion:_
```Python
                f'Failed to transform version in artifact {name}.')
```
___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 50 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56OsRvBY85d7kKcwsC:-N56OsRvBY85d7kKcwsD:undefined) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/driver/configurations/bazel/step-create-debian-archive.cmake#L50)):*
> ```CMake
>   if(NOT DEBIAN_RESULT_VARIABLE EQUAL 0)
>     set(DASHBOARD_FAILURE ON)
>     append_step_status("BAZEL DEBIAN ARCHIVE CREATION (ERROR CODE=${DEBIAN_RESULT_VARIABLE})" UNSTABLE)
> ```





_Suggestion:_
```CMake
append_step_status(
  "BAZEL DEBIAN ARCHIVE CREATION (ERROR CODE=${DEBIAN_RESULT_VARIABLE})"
  UNSTABLE)
```


<!-- Sent from Reviewable.io -->

2022-06-22 23:18 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/upload-to-aws.py` line 167 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N52-S_z1oMthiDl7WbO:-N5CebHGB71iamVeQe4S:b-z3naty) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/cb7996a8bb1878e0d5205372d4025249151e7d1d/tools/upload-to-aws.py#L167)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

The first half of your comment seems to be outdated?
</blockquote></details>

Yes, we want it for nightly and continuous.  We also want to fail it which was the main point.
___
*[`tools/upload-to-aws.py` line 170 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56LP9q1hUadduf5_Jw:-N5CeP_G55uG2y59wkre:b5qkr3l) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L170)):*
Working, no ... it is not ok good catch!  Easiest to just special-case the debian release, with the update:

```py
>>> import re
>>> name = "drake-dev_0.0.20220620-1_amd64-focal.deb"
>>> m = re.match(r'^drake-[^-]+(-[0-9a-f]{40})?-(.*)$', name)
>>> residue = m.group(2)
>>> name.startswith('drake-dev_0.0')
True
>>> f'drake-dev_latest-{residue}'
'drake-dev_latest-1_amd64-focal.deb'
```

New fake nightly build (it will test both cases, `.tar.gz` and `.deb` are both uploaded):

https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/29/
___
*[`tools/upload-to-aws.py` line 193 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56LcFU97SjUNS5ABXm:-N5Cf-LM3YqEfApZfYVb:bkfnt1o) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L193)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I don't think we need to aggressively wrap as late as possible; breaking after the `;` instead is prettier. Although, with this being promoted to an error, I don't think we need everything after the `;` anyway.
</blockquote></details>

Done, `f"Failed to transform version in artifact {name} to 'latest'."` for clarity.
___
*[`tools/upload-to-aws.py` line 165 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N5ChJnPCpsT_diQ62_u:-N5ChJnPCpsT_diQ62_v:b-v47qia) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/437aa19d59e1e4ecf9b43d4734223d85e79bea86/tools/upload-to-aws.py#L165)):*
> ```Python
>     # if not options.experimental:
>     # TODO(svenevs): testing fake nightly latest upload
>     if True:
> ```

Working, obliterate this when final names are confirmed
___
*[`driver/configurations/bazel/step-create-debian-archive.cmake` line 50 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56OsRvBY85d7kKcwsC:-N5CfwYZ-qQI7couN0gT:b32w0x) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/driver/configurations/bazel/step-create-debian-archive.cmake#L50)):*
> ```CMake
>   if(NOT DEBIAN_RESULT_VARIABLE EQUAL 0)
>     set(DASHBOARD_FAILURE ON)
>     append_step_status("BAZEL DEBIAN ARCHIVE CREATION (ERROR CODE=${DEBIAN_RESULT_VARIABLE})" UNSTABLE)
> ```

OK


<!-- Sent from Reviewable.io -->

2022-06-23 00:29 UTC, svenevs reviewed
> Reviewed 1 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: all files reviewed, 1 unresolved discussion (waiting on @mwoehlke-kitware)

___
*[`tools/upload-to-aws.py` line 170 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56LP9q1hUadduf5_Jw:-N5CwBBDAIY_sOeFZW2i:b-sg3qql) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L170)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, no ... it is not ok good catch!  Easiest to just special-case the debian release, with the update:

```py
>>> import re
>>> name = "drake-dev_0.0.20220620-1_amd64-focal.deb"
>>> m = re.match(r'^drake-[^-]+(-[0-9a-f]{40})?-(.*)$', name)
>>> residue = m.group(2)
>>> name.startswith('drake-dev_0.0')
True
>>> f'drake-dev_latest-{residue}'
'drake-dev_latest-1_amd64-focal.deb'
```

New fake nightly build (it will test both cases, `.tar.gz` and `.deb` are both uploaded):

https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/29/
</blockquote></details>

Done, good to go -- uploaded files:

- tgz:
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-20220622233710-0cbe388e250d12d4ea44d762d65f14043abd0eb3-focal.tar.gz
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-20220622233710-0cbe388e250d12d4ea44d762d65f14043abd0eb3-focal.tar.gz.sha512
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-latest-focal.tar.gz
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-latest-focal.tar.gz.sha512
- deb:
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-dev_0.0.20220622233710-0cbe388e250d12d4ea44d762d65f14043abd0eb3-1_amd64-focal.deb
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-dev_0.0.20220622233710-0cbe388e250d12d4ea44d762d65f14043abd0eb3-1_amd64-focal.deb.sha512
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-dev_latest-1_amd64-focal.deb
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-dev_latest-1_amd64-focal.deb.sha512

The regex has already been tested in previous builds against `continuous` and `nightly`, the change here confirms that on the python side the `name` is getting set correctly for both `deb` and `not deb`.
___
*[`tools/upload-to-aws.py` line 165 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N5ChJnPCpsT_diQ62_u:-N5CxXkt89Cc0Jhr00mu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/437aa19d59e1e4ecf9b43d4734223d85e79bea86/tools/upload-to-aws.py#L165)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, obliterate this when final names are confirmed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-24 15:43 UTC, mwoehlke-kitware requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: all files reviewed, 2 unresolved discussions (waiting on @svenevs)

___
*[`tools/upload-to-aws.py` line 170 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56LP9q1hUadduf5_Jw:-N5LLOu9CvbZ21Tc0rYt:bk340zd) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L170)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Done, good to go -- uploaded files:

- tgz:
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-20220622233710-0cbe388e250d12d4ea44d762d65f14043abd0eb3-focal.tar.gz
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-20220622233710-0cbe388e250d12d4ea44d762d65f14043abd0eb3-focal.tar.gz.sha512
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-latest-focal.tar.gz
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-latest-focal.tar.gz.sha512
- deb:
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-dev_0.0.20220622233710-0cbe388e250d12d4ea44d762d65f14043abd0eb3-1_amd64-focal.deb
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-dev_0.0.20220622233710-0cbe388e250d12d4ea44d762d65f14043abd0eb3-1_amd64-focal.deb.sha512
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-dev_latest-1_amd64-focal.deb
    - https://drake-packages.csail.mit.edu/drake/experimental/drake-dev_latest-1_amd64-focal.deb.sha512

The regex has already been tested in previous builds against `continuous` and `nightly`, the change here confirms that on the python side the `name` is getting set correctly for both `deb` and `not deb`.
</blockquote></details>

Instead of adding conditional branches, why not just update the regex? Here's the complete code:
```python
        m = re.match(r'^(drake-(dev_)?)[^-]+(-[0-9a-f]{40})?-(.*)$', name)
        if m is not None:
            prefix = m.group(1)  # 'drake-' or 'drake-dev_'
            residue = m.group(4)  # '<stuff>'
            name = f'{prefix}-latest-{residue}'
```
___
*[`tools/upload-to-aws.py` line 176 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N5LMGH890YflNu8PiO4:-N5LMGH890YflNu8PiO5:undefined) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/8cc0d1416d410d11233226b7f8bfa82340b1fb85/tools/upload-to-aws.py#L176)):*
> ```Python
>         # Generally:
>         #   drake-<version>-<stuff>
>         #   drake-dev_0.0.<version>-<stuff>
> ```





_Suggestion:_
```Python
        #   drake-[dev_]<version>-<stuff>
```


<!-- Sent from Reviewable.io -->

2022-06-24 19:22 UTC, mwoehlke-kitware reviewed
> Reviewed 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: all files reviewed, 2 unresolved discussions (waiting on @svenevs)



<!-- Sent from Reviewable.io -->

2022-07-06 02:50 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: all files reviewed, 2 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/upload-to-aws.py` line 170 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56LP9q1hUadduf5_Jw:-N6GO0dc1mjdvqulafNp:b1uadcy) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L170)):*
I don't see a good way to accommodate this using regex exclusively, using the above we'll end up with

```py
>>> f'{prefix}-latest-{residue}'
'drake-dev_-latest-1_amd64-focal.deb'
#          ^ problem, deb wants `drake-dev_{version}` (underscore, not dash)
```

But for all the others we want `-latest`.  We could split into `regex_1|regex_2` with quite a bit of duplication, but personally I think that's going to be harder to maintain long term.  I'd prefer to just special case in code what needs to be.

In the above we'd need to check something like

```py
if prefix.endswith("_"):
    name = f'{prefix}latest-{residue}'
else:
    name = f'{prefix}-latest-{residue}'
```

Do you see a non-if way of excluding `-` before `latest` for the deb?  If not, do you have a preference for the current implementation or the new regex you propose above?  I lean toward preferring the current implementation, but don't really have a strong preference.


<!-- Sent from Reviewable.io -->

2022-07-06 14:36 UTC, mwoehlke-kitware commented
*[`tools/upload-to-aws.py` line 170 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56LP9q1hUadduf5_Jw:-N6IvFK-27x_DdS4L6av:b-dvsmzg) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L170)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

I don't see a good way to accommodate this using regex exclusively, using the above we'll end up with

```py
>>> f'{prefix}-latest-{residue}'
'drake-dev_-latest-1_amd64-focal.deb'
#          ^ problem, deb wants `drake-dev_{version}` (underscore, not dash)
```

But for all the others we want `-latest`.  We could split into `regex_1|regex_2` with quite a bit of duplication, but personally I think that's going to be harder to maintain long term.  I'd prefer to just special case in code what needs to be.

In the above we'd need to check something like

```py
if prefix.endswith("_"):
    name = f'{prefix}latest-{residue}'
else:
    name = f'{prefix}-latest-{residue}'
```

Do you see a non-if way of excluding `-` before `latest` for the deb?  If not, do you have a preference for the current implementation or the new regex you propose above?  I lean toward preferring the current implementation, but don't really have a strong preference.
</blockquote></details>

Ack. The only change needed should be `{prefix}-latest` → `{prefix}latest`? (The wheels/tarballs would also have two `-`s as proposed! :flushed:)


<!-- Sent from Reviewable.io -->

2022-07-07 02:03 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/upload-to-aws.py` line 170 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56LP9q1hUadduf5_Jw:-N6LMmGf7Omjzt7iip4f:b-9pjc2o) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L170)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Note 1 (original suggestion):
```python
>>> name = 'drake-20220706010644-b98434ac68fd675ab10cca07c4aadbe512dae638-focal.tar.gz'
>>> m = re.match(r'^(drake-(dev_)?)[^-]+(-[0-9a-f]{40})?-(.*)$', name)
>>> prefix = m.group(1)
>>> residue = m.group(4)
>>> f'{prefix}-latest-{residue}'
'drake--latest-focal.tar.gz'
```

Note 2 (amended suggestion):
```python
>>> name = 'drake-dev_0.0.20220622233710-0cbe388e250d12d4ea44d762d65f14043abd0eb3-1_amd64-focal.deb'
>>> m = re.match(r'^(drake-(dev_)?)[^-]+(-[0-9a-f]{40})?-(.*)$', name)
>>> prefix = m.group(1)
>>> residue = m.group(4)
>>> f'{prefix}latest-{residue}'
'drake-dev_latest-1_amd64-focal.deb'
```
</blockquote></details>

Added, new jobs to check on final uploaded names tomorrow before approving:

- https://drake-jenkins.csail.mit.edu/view/Wheel/job/linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release/49/console
- https://drake-jenkins.csail.mit.edu/view/Wheel/job/mac-big-sur-unprovisioned-clang-wheel-experimental-snopt-mosek-release/11/console
- https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/31/console
___
*[`tools/upload-to-aws.py` line 176 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N5LMGH890YflNu8PiO4:-N6LKZ830vDid8kKKWiu:bw0fo1e) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/8cc0d1416d410d11233226b7f8bfa82340b1fb85/tools/upload-to-aws.py#L176)):*
> drake-[dev_]<version>-<stuff>

This is not the same.  It's got the same hyphen issue as before, one option is `drake-<version>-<stuff>` (hyphen before `version`), another is `drake-dev_0.0.<version>` without a hyphen before `<version>`.  I personally would rather include full examples of the archive names for everything in the comments (tgz, deb, and wheels) because it makes it easier for us the developers, but you already requested abbreviating it for line length.

Any additional changes requested to this code block and I would strongly advocate for splitting this logic into cases by file extension.  Using a single regular expression to rule them all is harder to maintain and will break again if any new kinds of uploads are added.  I also don't have any interest and retesting every single version each time we make a change here.


<!-- Sent from Reviewable.io -->

2022-07-08 00:26 UTC, svenevs reviewed
Unless there are other issues with this please merge it when you finalize your review so that it gets in for the weekend.  Kitware is on buildcop right now which is a good time to deal with it, if there are issues with the nightlies or continuous builds then they will be addressed in a followup.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-:-N6QBSdS-cBsnI3I7ZgE:b-gac12m)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/upload-to-aws.py` line 170 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N56LP9q1hUadduf5_Jw:-N6QApTS1k7RrjXq5yw3:bbmhjwj) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/b2aaa81d9aeee7484d843c75aa3d1de22e309f5a/tools/upload-to-aws.py#L170)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Added, new jobs to check on final uploaded names tomorrow before approving:

- https://drake-jenkins.csail.mit.edu/view/Wheel/job/linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release/49/console
- https://drake-jenkins.csail.mit.edu/view/Wheel/job/mac-big-sur-unprovisioned-clang-wheel-experimental-snopt-mosek-release/11/console
- https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/31/console
</blockquote></details>

OK, I forgot that in order to officially test it we have to tweak the script to convince it to do `latest` since these are experimental builds.  Rather than doing that again, I scraped the artifact names from the logs.  AFAICT this will behave as we want, we cannot properly monitor nightly and continuous tracks until it is actually merged in.

```py
#!/usr/bin/env python3
import re

def to_latest(name):
    m = re.match(r'^(drake-(dev_)?)[^-]+(-[0-9a-f]{40})?-(.*)$', name)
    if m is not None:
        prefix = m.group(1)
        residue = m.group(4)
        name = f'{prefix}latest-{residue}'
        return name

archives = [
    "drake-20220707021822-5cd2df08d78e3bc280eb2a2133b1c2684025cd5a-focal.tar.gz",
    "drake-dev_0.0.20220707021822-5cd2df08d78e3bc280eb2a2133b1c2684025cd5a-1_amd64-focal.deb",
    "drake-0.0.2022.7.7.2.7.43+git5cd2df08-cp38-cp38-manylinux_2_31_x86_64.whl",
    "drake-0.0.2022.7.7.2.7.43+git5cd2df08-cp39-cp39-manylinux_2_31_x86_64.whl",
   "drake-0.0.2022.7.6.22.13.27+git5cd2df08-cp39-cp39-macosx_11_0_x86_64.whl",
]
for a in archives:
    print(f"Original: {a}")
    print(f"Latest:   {to_latest(a)}")
    print("*" * 44)
```

gives

```
Original: drake-20220707021822-5cd2df08d78e3bc280eb2a2133b1c2684025cd5a-focal.tar.gz
Latest:   drake-latest-focal.tar.gz
********************************************
Original: drake-dev_0.0.20220707021822-5cd2df08d78e3bc280eb2a2133b1c2684025cd5a-1_amd64-focal.deb
Latest:   drake-dev_latest-1_amd64-focal.deb
********************************************
Original: drake-0.0.2022.7.7.2.7.43+git5cd2df08-cp38-cp38-manylinux_2_31_x86_64.whl
Latest:   drake-latest-cp38-cp38-manylinux_2_31_x86_64.whl
********************************************
Original: drake-0.0.2022.7.7.2.7.43+git5cd2df08-cp39-cp39-manylinux_2_31_x86_64.whl
Latest:   drake-latest-cp39-cp39-manylinux_2_31_x86_64.whl
********************************************
Original: drake-0.0.2022.7.6.22.13.27+git5cd2df08-cp39-cp39-macosx_11_0_x86_64.whl
Latest:   drake-latest-cp39-cp39-macosx_11_0_x86_64.whl
********************************************
```

Seems like what we want for all of them.


<!-- Sent from Reviewable.io -->

2022-07-11 14:27 UTC, mwoehlke-kitware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/upload-to-aws.py` line 176 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N5LMGH890YflNu8PiO4:-N6hcz9P94TZrzaU7i75:bej1jzx) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/8cc0d1416d410d11233226b7f8bfa82340b1fb85/tools/upload-to-aws.py#L176)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

> drake-[dev_]<version>-<stuff>

This is not the same.  It's got the same hyphen issue as before, one option is `drake-<version>-<stuff>` (hyphen before `version`), another is `drake-dev_0.0.<version>` without a hyphen before `<version>`.  I personally would rather include full examples of the archive names for everything in the comments (tgz, deb, and wheels) because it makes it easier for us the developers, but you already requested abbreviating it for line length.

Any additional changes requested to this code block and I would strongly advocate for splitting this logic into cases by file extension.  Using a single regular expression to rule them all is harder to maintain and will break again if any new kinds of uploads are added.  I also don't have any interest and retesting every single version each time we make a change here.
</blockquote></details>

I'm not sure where the extra hyphen in your quote came from? I don't see it in the suggestion. Anyway, if we're going to be pedantic, then I think the second example should be `drake-[dev_]0.0.<timestamp>-<stuff>` or even `drake-[dev_]0.0.<timestamp>[-<commit>]-<stuff>`. The `0.0.` is part of `<version>`. OTOH, given .deb's quirk of using a hyphen before the (optional) commit, maybe it does make sense to keep a separate `drake-dev_<version>[-<commit>]-<stuff>`.

That all said, the advantage of having just `drake-[dev_]<version>-<stuff>` (note, no `-` after `[dev_]`) is that it matches the regex. And we do have the examples above that give more details.

WDYT?


<!-- Sent from Reviewable.io -->

2022-07-11 19:24 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/upload-to-aws.py` line 176 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N5LMGH890YflNu8PiO4:-N6idrK5CMutqSyQnvuH:b-axkfbp) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/8cc0d1416d410d11233226b7f8bfa82340b1fb85/tools/upload-to-aws.py#L176)):*
> drake-[dev_]- (bad quote by me)
>
> ...
>
> the advantage of having just `drake-[dev_]<version>-<stuff>`

This code is not straightforward to follow by just looking at the regex, and folding more comments into fewer just further obscures it.  Currently it's generalized how I prefer it: tgz, then deb, then wheel pattern.    I do not personally see the value in combining the tgz and deb versions and how that makes it easier to understand.  What do we gain in clarity by this one line?

> WDYT?

I believe the comment is accurate as is.  I'm also not interested in dragging this PR out any further over how to abbreviate it.  Your previous reply proposes 3 options.  Please state specifically which one you want / will approve so that I can finish this and move on to the followup work.  I don't believe bikeshedding this comment is a valuable use of either of our time.


<!-- Sent from Reviewable.io -->

2022-07-11 20:49 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/upload-to-aws.py` line 176 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-N5LMGH890YflNu8PiO4:-N6j0D3D-5uW8z84AtUD:b-dpsg5w) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/8cc0d1416d410d11233226b7f8bfa82340b1fb85/tools/upload-to-aws.py#L176)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I think the main point is that `0.0.<version>` seem very weird to me. The `0.0.` is *part of the version*, is it not? Why is it being separated? This would make sense if you wrote `0.0.<timestamp>`.

> This code is not straightforward to follow by just looking at the regex

I guess this seems to me like a reason *for* generalizing to a single comment that matches the regex, i.e. `drake-[dev_]<version>[-<commit>]-<stuff>`. That is what the regex matches, and my hope would be that documenting it in an "I don't speak PCRE" manner makes the code easier to understand.

> folding more comments into fewer just further obscures it

I guess I'm unclear on why "[a]b" is so much harder to read compared to "'b' or 'ab'"? I hope you are not under the impression that I am asking to simplify *all* of the comments to just `drake-[dev_]<version>[-<commit>]-<stuff>`! That was never intended by this thread; I am only proposing to change what is after `# Generally:` while retaining everything currently before that.

>  Please state specifically which one you want

I think I've made my inclination clear, but since you evidently have a strong dislike for it, I will clarify that I will accept any of the following (again, please *keep* everything before `# Generally:` as in the current PR!):

```
        # Generally:
        #   drake-[dev_]<version>[-<commit>]-<stuff>
```
-or-
```
        # Generally:
        #   drake-<version>-<stuff>
        #   drake-dev_<version>[-<commit>]-<stuff>
```
-or-
```
        # Generally:
        #   drake-<version>-<stuff>
        #   drake-dev_0.0.<timestamp>[-<commit>]-<stuff>
```

Comments:
- The first is not only the most succinct; yes, it takes slightly more mental gymnastics to see how it matches all of the preceding examples, but it then expresses the regex exactly.
- The second trades easier association with the more specific examples with somewhat harder association to the actual regex. (Pedantically, the former doesn't express that `drake-<version>-<commit>-<stuff>` would be parsed as such, but that's not really what we're trying to express with the comment, so meh.) Anyway, the following paragraph arguably covers that.
- TBH, I am somewhat concerned that the third will cease to be accurate as we move to more release automation (i.e. we may eventually have properly numbered releases in a `release` track, for which a 'latest' may make sense), but you appear to feel that the literal `0.0.` is important.

Any of those three would be satisfactory. I'm *trying* to not dictate. :slightly_smiling_face:
</blockquote></details>

OK, we coordinated offline since our wires were a bit crossed.  Went with option 1 for `Generally` :+1:


<!-- Sent from Reviewable.io -->

2022-07-11 20:50 UTC, mwoehlke-kitware approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157#-:-N6j0ksE9vHF_z1tEWJW:b-jbsf8z)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @svenevs)



<!-- Sent from Reviewable.io -->

2022-07-11 20:51 UTC, svenevs reviewed
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @svenevs)



<!-- Sent from Reviewable.io -->

2022-07-11 20:52 UTC, merged