[cache] Add cache server documentation and starter files
RobotLocomotion/drake-ci pull request #198
Opened 2023-02-07 02:10 UTC by svenevs

These files are running live on one of our cache servers, over time we will be migrating to a unified architecture and updating the relevant documentation of cache_server/README.

2023-02-07 02:14 UTC, svenevs commented
FYI review of README may be easier by viewing directly: https://github.com/RobotLocomotion/drake-ci/tree/feat/cache-server-infrastructure/cache_server

2023-02-07 02:56 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @svenevs)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdkPckD4U61Ch0_pVM:-NNdkPckD4U61Ch0_pVN:bdlnq07) (no related file):*
Working, I think we should consider adding GHA to

- `shellcheck` any `*.sh` files
- python linting
    - `black --target-version py38 --check --diff`
    - `mypy`
    - `flake8 --max-line-length 88`

___
___
*[`cache_server/cleanup_old_files.py` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdlA9y-ABxYe3r04Fb:-NNdlA9y-ABxYe3r04Fc:bb64jli) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/cleanup_old_files.py#L4)):*
> ```Python
> """Cleanup cache server data.
> 
> By default, **accessed** more than 3 days ago will be deleted.  Since different servers
> ```

Working, default 3 => 4 days
___
*[`cache_server/cleanup_old_files.py` line 131 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdlJsw6vwbhBB1DD41:-NNdlJsw6vwbhBB1DD42:b-lbqc4u) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/cleanup_old_files.py#L131)):*
> ```Python
>                     f_stat = f_path.stat()
> 
>                     # Convert the access time from unix time to datetime.  Skip if the
> ```

Working, `access time` => `access / modification time`
___
*[`cache_server/cleanup_old_files.py` line 138 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdlPWvBeTl8urVgoBR:-NNdlPWvBeTl8urVgoBS:b-3xoctv) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/cleanup_old_files.py#L138)):*
> ```Python
>                         continue
> 
>                     # Add anything accessed longer ago than the provided threshold.
> ```

Working, `accessed` => `accessed / modified`
___
*[`cache_server/cleanup_old_files.py` line 170 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdlWM54WAKwT8bEQ1e:-NNdlWM6Aki8FZN0Uq10:beri6ja) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/cleanup_old_files.py#L170)):*
> ```Python
>         # Print by access times first, gather data for dumping by size after.
>         if not summary_only:
>             print(f"==> By access times ({len(time_map)} total):")
> ```

Working, it may be `access times` or it may be `modified times`, format accordingly.
___
*[`cache_server/cleanup_old_files.py` line 175 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdlcbuCNYUUTlbN-bb:-NNdlcbuCNYUUTlbN-bc:b-o2xfht) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/cleanup_old_files.py#L175)):*
> ```Python
>                 file_path_size_bytes = time_map[key]
>                 size_bytes = sum(fpsb[1] for fpsb in file_path_size_bytes)
>                 # Two access times *may* end up having the same total size_bytes,
> ```

Working, `access` => `access / modified`
___
*[`cache_server/cleanup_old_files.py` line 196 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdllHG5IExCh9QoDbM:-NNdllHG5IExCh9QoDbN:b-xnqt99) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/cleanup_old_files.py#L196)):*
> ```Python
>         # Print out the most useful information last so it is readily available.
>         print(f"==> {str(self.root)}")
>         print(f"Found: {self.files_scanned} total files.")
> ```

Working, add printout about `access` or `modified` time and the time metric being used (print out the timedelta)
___
*[`cache_server/disk_usage_alert.sh` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdm5nX3eKTs0ffSs3y:-NNdm5nX3eKTs0ffSs3z:b-r7o06j) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/disk_usage_alert.sh#L12)):*
> ```Shell
> # both of these variables when configuring a new deployment.
> cache_mount_point="/dev/sdb1"
> cache_server_name="Drake Mac arm64 Cache Server"
> ```

Working, maybe it is better to put an invalid starting value for these and have the script error out if the defaults were not changed?

```bash
cache_mount_point="UPDATE"
cache_server_name="UPDATE"

if [[ "${cache_mount_point}" == "UPDATE" ]] || [[ "${cache_server_name}" == "UPDATE" ]]; then
    echo "The 'cache_mount_point' and 'cache_server_name' variables must be updated." >&2
    exit 1
fi
```
___
*[`cache_server/disk_usage_alert.sh` line 13 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdmqHqAzPjyokTtrUG:-NNdmqHqAzPjyokTtrUH:bi9w1r8) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/disk_usage_alert.sh#L13)):*
> ```Shell
> cache_mount_point="/dev/sdb1"
> cache_server_name="Drake Mac arm64 Cache Server"
> ```

Working, this needs to be run as `root`, enforce this.
___
*[`cache_server/disk_usage_alert.sh` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdmZJL8dPimdnMkj1W:-NNdmZJL8dPimdnMkj1X:b-nnm1yr) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/disk_usage_alert.sh#L32)):*
> ```Shell
> 
> # If utilization is above 85% then send a notification email.
> if [[ "${percent_used}" -gt 85 ]]; then
> ```

Working, it might be nice to enable a bypass to skip emailing or something?  Or change the emails it goes to? `BYPASS_EMAIL=stephen.mcdowell@kitware.com ./disk_usage_alerts.sh`?

Incentive: when setting up a server for the first time, you don't want to spam buildcop email lists.  That said, encouraging in the readme to edit away the emails (or use an array and encourage overwriting its value) may be better?  Basically, I don't like that you can't "try before you buy" in the current form.


<!-- Sent from Reviewable.io -->

2023-02-07 03:04 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: 0 of 5 files reviewed, 11 unresolved discussions

___
*[`cache_server/cleanup_old_files.py` line 195 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdopIk52vUNbeSWJXw:-NNdopIk52vUNbeSWJXx:bhc7okn) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/cleanup_old_files.py#L195)):*
> ```Python
> 
>         # Print out the most useful information last so it is readily available.
>         print(f"==> {str(self.root)}")
> ```

Working, it ran but the logging did not appear in `/var/log/syslog`, only thing that showed up: `Feb  7 03:00:01 tytrsr-ubuntu-01 CRON[33668]: (root) CMD (/cache/cleanup_old_files.py -s --days 4 /cache/toyotacache)`

Maybe we should just redirect to our own custom logfile location under `/cache/` (have the `cron` job append) and include the date / time here or instead switch to `logging` module?


<!-- Sent from Reviewable.io -->

2023-02-07 16:19 UTC, BetsyMcPhail submitted a review, later dismissed
The ARM jobs in CI seem to be communicating with the cache server as expected.
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-:-NNgf6XC6BB2UhCF0MIe:bslxmyj)* status: all files reviewed, 13 unresolved discussions (waiting on @svenevs)

___
*[`cache_server/README.md` line 31 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNgcS6W7h9JLX0Ju72c:-NNgcS6W7h9JLX0Ju72d:bhswi3h) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/README.md#L31)):*
> ```Markdown
> to simply setting the `bazel` cache server entries to different subdirectories.
> 
> 1. A consuming build will configure [`remote.bazelrc.in`][remote_bazelrc]:
> ```

I'm not sure what is meant by "consuming" here? Builds using the cache?
 
___
*[`cache_server/README.md` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNgcD8E7iC_Vr9hw4Qa:-NNgcD8E7iC_Vr9hw4Qb:b-fr4r60) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/README.md#L33)):*
> ```Markdown
> 1. A consuming build will configure [`remote.bazelrc.in`][remote_bazelrc]:
> 
>    i. If this build is populating the cache (`nightly`, `continuous`) or reading
> ```

Formatting for the sub-items in this list isn't working as expected.


<!-- Sent from Reviewable.io -->

2023-02-08 22:00 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: 3 of 6 files reviewed, 13 unresolved discussions (waiting on @BetsyMcPhail)

___
*[`cache_server/cleanup_old_files.py` line 195 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdopIk52vUNbeSWJXw:-NNn1G8Z3URElOuzWMDR:b-zgj6o6) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/cleanup_old_files.py#L195)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, it ran but the logging did not appear in `/var/log/syslog`, only thing that showed up: `Feb  7 03:00:01 tytrsr-ubuntu-01 CRON[33668]: (root) CMD (/cache/cleanup_old_files.py -s --days 4 /cache/toyotacache)`

Maybe we should just redirect to our own custom logfile location under `/cache/` (have the `cron` job append) and include the date / time here or instead switch to `logging` module?
</blockquote></details>

Update: see new `disk_usage_alerts.py`.  I propose we simply log to file, rather than using cron's email by default stance.  That's running live now, example log:

```console
root@tytrsr-ubuntu-01:/home/administrator# cat /cache/logs/disk_usage_alert.log 
2023-02-08 21:46:01 :: ================================================================================
2023-02-08 21:46:01 :: 
2023-02-08 21:46:01 :: - Mount: /cache/toyotacache
2023-02-08 21:46:01 :: - Used:  343.9986 GB
2023-02-08 21:46:01 :: - Free:  122.0671 GB
2023-02-08 21:46:01 :: - Total: 491.0813 GB
2023-02-08 21:46:01 :: - %Used: 70.05%
2023-02-08 21:46:01 :: 
2023-02-08 21:46:01 :: ==> 70.04921139102815% usage is adequately beneath 80.0%!
```

The emails cron was sending out are going to nobody, but are also cc'ing `postmaster@gmail.com` :scream:  If we're OK with this approach then I'll add it to the file cleanup script.  For right now I'm just moving that cron job to redirect everything to `/dev/null` to avoid the emails.


<!-- Sent from Reviewable.io -->

2023-02-17 20:10 UTC, mwoehlke-kitware reviewed
This is incomplete, mostly covering the README. (Lots of small grammar suggestions, a few points that were unclear.)

2023-02-21 17:40 UTC, mwoehlke-kitware reviewed
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: 4 of 6 files reviewed, 35 unresolved discussions (waiting on @BetsyMcPhail and @svenevs)

___
*[`cache_server/README.md` line 76 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NOox7Jp9h-oEzJQHZvl:-NOox7Jp9h-oEzJQHZvm:b-uy713c) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/README.md#L76)):*
> ```Markdown
>     #
>     # Cache (over)utilization alerting: run ~7am eastern.
>     0 12    * * *   root    /cache/disk_usage_alert.py --name mac-arm64 --log-file /cache/logs/disk_usage_alert.log /cache/toyotacache
> ```

Outdated? The only named argument `disk_usage_alert.py` takes appears to be `--threshold`?


<!-- Sent from Reviewable.io -->

2023-04-06 00:47 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: 3 of 8 files reviewed, 36 unresolved discussions (waiting on @BetsyMcPhail and @mwoehlke-kitware)

___
*[`cache_server/health_check.bash` line 17 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NSJ0zlJ2sIvpiEm7WJr:-NSJ0zlKCwaBql6KnYf7:bg25lzo) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/dfcfa65795abbb85ef4fc9efeef95e109ef6a9aa/cache_server/health_check.bash#L17)):*
> ```Shell
> # TODO(svenevs): this will get added to jenkins credentials instead and we are
> # expected to be able to login to the cache server directly from there.
> aws s3 cp \
> ```

working, there may be a better way to do this, to be discussed in f2f

Skeleton of jenkins-piloted cache server check is in,

- https://drake-jenkins.csail.mit.edu/view/Cache%20Server/job/mac-arm-monterey-cache-server-health-check/5/consoleFull
- (xfail) https://drake-jenkins.csail.mit.edu/view/Cache%20Server/job/mac-arm-monterey-cache-server-health-check/6/consoleFull


<!-- Sent from Reviewable.io -->

2023-04-06 15:29 UTC, BetsyMcPhail reviewed
Removing myself as reviewer -@betsy.mcphail

> Reviewed 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-:-NSMAnmxBh5thK3n_LZs:b-fn3mwf)* status: all files reviewed, 36 unresolved discussions (waiting on @svenevs)



<!-- Sent from Reviewable.io -->

2023-04-13 19:57 UTC, svenevs reviewed
> Reviewed 5 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: 8 of 10 files reviewed, 31 unresolved discussions (waiting on @BetsyMcPhail and @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdkPckD4U61Ch0_pVM:-NSvwoBJ7dMfnnJaIUfI:b-qbdq3c) (no related file):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, I think we should consider adding GHA to

- `shellcheck` any `*.sh` files
- python linting
    - `black --target-version py38 --check --diff`
    - `mypy`
    - `flake8 --max-line-length 88`
</blockquote></details>

done, i'm doing it myself, we really should be enforcing these long term though

___
___
*[`cache_server/health_check.bash` line 17 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NSJ0zlJ2sIvpiEm7WJr:-NSvxB7L2sJFks9Uqy4M:b-qj1sw0) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/dfcfa65795abbb85ef4fc9efeef95e109ef6a9aa/cache_server/health_check.bash#L17)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, there may be a better way to do this, to be discussed in f2f

Skeleton of jenkins-piloted cache server check is in,

- https://drake-jenkins.csail.mit.edu/view/Cache%20Server/job/mac-arm-monterey-cache-server-health-check/5/consoleFull
- (xfail) https://drake-jenkins.csail.mit.edu/view/Cache%20Server/job/mac-arm-monterey-cache-server-health-check/6/consoleFull
</blockquote></details>

done, downloading ssh key is easiest and fastest, we do it elsewhere in this repo (e.g., for snopt) as well
___
*[`cache_server/README.md` line 31 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNgcS6W7h9JLX0Ju72c:-NSw8Kst9C_9ioBAyvhM:br991d5) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/README.md#L31)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

I'm not sure what is meant by "consuming" here? Builds using the cache?
 
</blockquote></details>

done, `consuming` => `cached`
___
*[`cache_server/README.md` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNgcD8E7iC_Vr9hw4Qa:-NSw8U002bVYM0H4UpWa:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/README.md#L33)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Formatting for the sub-items in this list isn't working as expected.
</blockquote></details>

done
___
*[`cache_server/README.md` line 13 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh8-r2-13:-NSw87Ye7wGJZojbreGx:bdek3t1) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/README.md#L13)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

This reads rather oddly (and is also missing from other servers, but I guess that's part of the TODO?). Maybe something like "Total storage: 500GB (current), 1TB (anticipated)"?
</blockquote></details>

done, removed
___
*[`cache_server/README.md` line 31 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh8-r2-31:-NSw8NHU4OV-d-s0pqmJ:b-ovb10) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/README.md#L31)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

What is a "consuming" build? Maybe reword this? Similarly, adding "to specify" at the end might make the following points clearer.
</blockquote></details>

done, `consuming` => `cached`, bullet points that follow distinguish cache populate vs cache read
___
*[`cache_server/README.md` line 49 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh8-r2-49:-NSw8xTmAHZEtwYzHEea:b-s1uhec) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/README.md#L49)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

```suggestion
2. The cache server must **always** support being able to `GET /`, as
   [`cache.cmake`][cache_cmake] performs this step at the beginning to confirm
   the remote cache can be communicated with. If `GET /` fails, the remote
   cache is disabled.
```

Also, Richard Dean Anderson is [not amused](https://www.youtube.com/watch?v=50OXJ5AT3ms), although no obvious alternatives come to mind.
</blockquote></details>

done, i think, reworded at least
___
*[`cache_server/README.md` line 51 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh8-r2-51:-NSwBSf28LEQwJeFNLcS:bk8a2k0) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/README.md#L51)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

```suggestion
3. Each server should have a `cron` job running each evening to clean up older
```
"Cleanup", while a legitimate *noun*, is not a verb. Alternatively, "to remove older..." works equally well.
</blockquote></details>

working, about to rename 
___
*[`cache_server/README.md` line 53 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh8-r2-53:-NSwBU4pB_tCjOdrZ3Sv:b-21kn0l) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/README.md#L53)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

```suggestion
   files.  This is managed by [`cleanup_old_files.py`](cleanup_old_files.py).
   Here is a sample entry in `/etc/crontab`:
```

(Similar, below.)
</blockquote></details>

working, renaming
___
*[`cache_server/README.md` line 65 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh8-r2-65:-NSw96zZ7j6P2-6HgzI-:brkdh14) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/README.md#L65)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

It might be worth rewording or adding quotes or something here to make clear that this is referring to HTTP 500 and not exactly five hundred errors.
</blockquote></details>

done, section moved and improved
___
*[`cache_server/README.md` line 76 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NOox7Jp9h-oEzJQHZvl:-NSw94HrC2O_7t-aajh8:b-8r7b5a) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/README.md#L76)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Outdated? The only named argument `disk_usage_alert.py` takes appears to be `--threshold`?
</blockquote></details>

done, yes that went stale
___
*[`cache_server/README.md` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh8-r2-88:-NSw9lU5-6IcEymnqZfZ:bwvioj2) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/README.md#L88)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I'm not sure what this sentence is trying to convey?

Also (sorry for the unnecessary extra context):
```suggestion
scripts are placed in `/cache` directly.  Keeping a clone of `drake-ci` runs the
risk of accidentally overwriting cache-server specific data such as which device
mounts the storage or how often cleanup should happen.
```
</blockquote></details>

done, section rewritten
___
*[`cac [...]

2023-04-13 20:45 UTC, svenevs commented on cache_server/cleanup_old_files.py
> +By default, **accessed** more than 3 days ago will be deleted.  Since different servers
good catch!  `files` added

2023-04-13 20:46 UTC, svenevs commented on cache_server/cleanup_old_files.py
> +to create the final timedelta, and each must be greater than or equal to zero.  See:
done, good call -- changed to `non-negative`

2023-04-13 20:46 UTC, svenevs commented on cache_server/cleanup_old_files.py
> +    The default for days is always 4, if you desire to delete all files that have not
ok, fixed

2023-04-13 20:46 UTC, svenevs commented on cache_server/cleanup_old_files.py
> +    MB, KB, or Bytes (all base 1024).  The largest whole unit available is chosen."""
ok, `GB` => `GiB` and friends fixed.  I don't like the alternate implementation, it's not about LOC but something for somebody else to be able to review and easily understand.  Alternate is clever, but not clear.  We only ever need to deal with GiB, even if its reporting TiB (which it won't be because of our total space used here), this is just to help the human reading the logs.

work for you?

2023-04-13 21:14 UTC, svenevs reviewed
OK final review is ready, taking linux server live tomorrow based on these instructions.

> Reviewed 6 of 8 files at r9.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-:-NSwSuFY34Y42cRgMJDL:b-z69orw)* status: 9 of 12 files reviewed, 26 unresolved discussions (waiting on @BetsyMcPhail and @mwoehlke-kitware)

___
*[`cache_server/README.md` line 134 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh8-r2-134:-NSwSqDlB8SkGsv04eDs:b-7rl0jf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/README.md#L134)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

done, timezones fixed
</blockquote></details>

done,
___
*[`cache_server/cleanup_old_files.py` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdlA9y-ABxYe3r04Fb:-NSwQFaJ11HMwlgBtioV:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/cleanup_old_files.py#L4)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, default 3 => 4 days
</blockquote></details>

done
___
*[`cache_server/cleanup_old_files.py` line 131 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdlJsw6vwbhBB1DD41:-NSwQv4Y3XIK2cRfgVaA:b-7rl0jf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/cleanup_old_files.py#L131)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, `access time` => `access / modification time`
</blockquote></details>

done,
___
*[`cache_server/cleanup_old_files.py` line 138 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdlPWvBeTl8urVgoBR:-NSwSLnc3KRFL16xA1I1:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/cleanup_old_files.py#L138)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, `accessed` => `accessed / modified`
</blockquote></details>

done
___
*[`cache_server/cleanup_old_files.py` line 170 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdlWM54WAKwT8bEQ1e:-NSwSNap-TK9Y0uohf57:b-7rl0jd) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/cleanup_old_files.py#L170)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, it may be `access times` or it may be `modified times`, format accordingly.
</blockquote></details>

done.
___
*[`cache_server/cleanup_old_files.py` line 175 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdlcbuCNYUUTlbN-bb:-NSwSost2-EAnHSb-M2T:b-7rl0jd) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/30a0bf5886e0f9bfa635c45a15afc337747cef47/cache_server/cleanup_old_files.py#L175)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, `access` => `access / modified`
</blockquote></details>

done.
___
*[`cache_server/cleanup_old_files.py` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh9-r2-2:-NSwQBh18UCx3BZxd0kM:bdeurwr) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/cleanup_old_files.py#L2)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

```suggestion
"""Clean up cache server data.
```
</blockquote></details>

done, renamed
___
*[`cache_server/cleanup_old_files.py` line 4 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh9-r2-4:-NSwQEPf6rae7EmyGshM:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/cleanup_old_files.py#L4)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

good catch!  `files` added
</blockquote></details>

done
___
*[`cache_server/cleanup_old_files.py` line 10 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh9-r2-10:-NSwQHXY93Rz9waVz1HX:b-7rl0jf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/cleanup_old_files.py#L10)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

done, good call -- changed to `non-negative`
</blockquote></details>

done,
___
*[`cache_server/cleanup_old_files.py` line 16 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh9-r2-16:-NSwQMKh90zt1c7c1hZV:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/cleanup_old_files.py#L16)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

ok, fixed
</blockquote></details>

done
___
*[`cache_server/cleanup_old_files.py` line 28 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh9-r2-28:-NSwQOI07F-xfurytlB4:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/cleanup_old_files.py#L28)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

`__future__` imports should always be first.  fixed the rest, without blank line, using `flake8-import-order` locally :+1:
</blockquote></details>

done
___
*[`cache_server/cleanup_old_files.py` line 33 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh9-r2-33:-NSwQPlg7jLb323G85_L:b-xqhcbf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/cleanup_old_files.py#L33)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

ok, `GB` => `GiB` and friends fixed.  I don't like the alternate implementation, it's not about LOC but something for somebody else to be able to review and easily understand.  Alternate is clever, but not clear.  We only ever need to deal with GiB, even if its reporting TiB (which it won't be because of our total space used here), this is just to help the human reading the logs.

work for you? 
</blockquote></details>

done from my perspective
___
*[`cache_server/cleanup_old_files.py` line 50 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh9-r2-50:-NSwQVi216X6uKHnFs2n:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/cleanup_old_files.py#L50)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

done, rounded values to `2`
</blockquote></details>

done
___
*[`cache_server/cleanup_old_files.py` line 136 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh9-r2-136:-NSwSH-d-FzDT7O8F81b:bo705vf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/cleanup_old_files.py#L136)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Isn't this redundant? Or does `timedelta` not handle "negative" deltas?
</blockquote></details>

Possibly?  see comment above, ran it by Betsy and she agreed.  This is a safeguard against the case where pruning script starts running, but a cache job starts uploading things _after_.  It may very well be redundant based on the below:

```py
if (self.start_time - time_query) >= delta_max:
```

but I'd prefer to have the safeguard since there might be some obtuse edge case with user inputs or something?  Basically, it doesn't add much overhead and  [...]

2023-04-14 18:38 UTC, svenevs reviewed
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: 10 of 12 files reviewed, 27 unresolved discussions (waiting on @BetsyMcPhail and @mwoehlke-kitware)

___
*[`cache_server/health_check.bash` line 14 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NT02wU24zC4H4j8s8Mz:-NT02wU24zC4H4j8s8N-:b29e4xf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/163995cf714a3f76165259018d9b4ca5dd17013b/cache_server/health_check.bash#L14)):*
> ```Shell
>   $2: The login uri of the cache server.  For the MacStadium server it should be
>       the same as $1.  For the linux cache server on AWS, there is a different
>       ip address (view the instance on AWS EC2 to see).
> ```

working, some serious traumas in choosing the right values for these, answer changes depending on where you are running the script.  still identifying what ip addresses I actually need


<!-- Sent from Reviewable.io -->

2023-04-14 20:33 UTC, mwoehlke-kitware requested changes
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: 10 of 12 files reviewed, 21 unresolved discussions (waiting on @BetsyMcPhail and @svenevs)

___
*[`cache_server/README.md` line 53 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh8-r2-53:-NT05R076crv9PUlI7Ck:b-x9leu) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/README.md#L53)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, renaming
</blockquote></details>

Note that the actual suggestion here was `s/,/.  Here is/`. (Not that renaming `cleanup` isn't also good!)


<!-- Sent from Reviewable.io -->

2023-04-19 19:28 UTC, svenevs reviewed
added changes, please resolve the conversations in reviewable that list you as blocking. `health_check.bash` is WIP, please ignore that script for now until I've got final changes

> Reviewed 2 of 2 files at r12.
> Dismissed @BetsyMcPhail from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-:-NTPz4ip77aTP44CaIiV:b-csdc4d)* status: 9 of 12 files reviewed, 28 unresolved discussions (waiting on @BetsyMcPhail and @mwoehlke-kitware)

___
*[`cache_server/health_check.bash` line 7 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKsPZ255tP8O1f_T0b:-NTPVKb04EmvKN9GVfsh:b2i6pfs) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L7)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Suggestion: `Arguments:`. Also, it's usual to repeat the argument *name*, not e.g. `$1`.
</blockquote></details>

working, we're still establishing what the actual names and arguments are :confused:
___
*[`cache_server/health_check.bash` line 9 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKsjYB9AK4ANRu4N1H:-NTPVH_dDvqOb8TRMjDq:bd9adub) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L9)):*
> ```Shell
> Args:
>   $1: The server ip address of the cache server to health check.  This should
>       be the same value `DASHBOARD_REMOTE_CACHE` in
> ```

done, good catch
___
*[`cache_server/health_check.bash` line 16 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKsznYAE_EvprG29-M:-NTPWa1jBVQB2j9Xs5qj:b-it3n31) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L16)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

There seems to be at least a comma missing, though "the following steps," might be better than just a comma.
</blockquote></details>

why does it need to change?  grammatically `:` and then ordered list is valid
___
*[`cache_server/health_check.bash` line 31 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKvOGF2VYEuZKpB34C:-NTPWtKP6BpWy0KydJIA:b-gntwby) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L31)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

More "$1"/"$2".

Also for your consideration (don't feel strongly about these):
</blockquote></details>

done, mostly, pending 1/2 discussion elsewhere.  added `:` as requested, but `connect/you` kept rather than `Connect/You` (not a new sentence)
___
*[`cache_server/health_check.bash` line 34 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKrMOR7HE8zzDH4Xlk:-NTPX2mN5YflLymyg7Ce:b-h6d1ma) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L34)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Hmm, this says "URI", but it seems it wants a hostname? In general there seems to be some IP/URI disagreement in the documentation.
</blockquote></details>

working, this is still being established.  $1 must be an ip address.  $2 it depends ... jenkins kinks need to be finished first
___
*[`cache_server/health_check.bash` line 39 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKr6_hCGbl7ui3u82E:-NTPY-Bp6QTmLm2SLaYV:b-axo110) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L39)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Besides suggesting `readonly`, it seems this should happen *after* testing for the correct number of arguments?
</blockquote></details>

done, good call -- moved below usage checks
___
*[`cache_server/health_check.bash` line 41 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKwFKI1bff0J-3Ajy3:-NTPY4gt2f93ZNwI2rm2:b-1sfb8k) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L41)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I'm a little confused here. The logic seems to be "don't let this ron on macOS", but the comment includes extra steps needed to run on macOS? Maybe the comment should read "would also need", or omit that sentence?
</blockquote></details>

working, because it is probably about to change to need to run on macOS again re ip / firewall issues from jenkins
___
*[`cache_server/health_check.bash` line 57 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKxMmmAj5zslDOBRs1:-NTPZ0u42Dkj8VdoWYLC:bz8g85w) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L57)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

FYI, the usual pattern is `cd "$(dirname "${BASH_SOURCE}")" && pwd)`. The `-P` is fine, though I wonder a) if it's needed, or b) if other places should also be using it. I don't think the `--` is needed, nor eating the output of `cd` (in fact, if `cd` fails, it might be nice to see why). OTOH, the `&&` might be important.
</blockquote></details>

done, with minor differences.  I care very little about the scenarios where things might go wrong, worst case script cannot write to there and it will fail on download.  NBD as far as we're concerned, we control the environments this runs in and can always download there.
___
*[`cache_server/health_check.bash` line 66 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKyVTo35HL0aw9mCQX:-NTPuXIX2GzRzRZl6vQb:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L66)):*
> ```Shell
> 
> # This file should already live on the cache server in this exact location.
> # If anything goes wrong (script not there, ssh hangs) the below command will
> ```

done
___
*[`cache_server/health_check.bash` line 71 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKyhvPEuNTkBwhnEq2:-NTPu_ls6hy3GYM2o1Np:b-2fvdfx) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L71)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

"finger prints" → "fingerprints". Also, not sure what the first sentence is saying; 'requires logging into the remote server as root'?
</blockquote></details>

done, reworded, yeah the monitoring scripts being called for disk usage need to run as root (default login users do not have permissions to view them, owned by www-data or nginx user)
___
*[`cache_server/health_check.bash` line 81 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKz5eTEu6y7GYewPKG:-NTPw6DnEQ7CZVBGewbc:b-83eamh) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L81)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

If the remote command failed, we will never get here? This might belong in a `trap`?
</blockquote></details>

done, good call, trapped it up above after download
___
*[`cache_server/README.md` line 51 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh8-r2-51:-NTPwITo9ZTvlgEJ78Oi:bnp2xmp) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_ [...]

2023-04-19 19:55 UTC, svenevs reviewed
> Reviewed 1 of 1 files at r13.
> Dismissed @BetsyMcPhail from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: 9 of 12 files reviewed, 18 unresolved discussions (waiting on @mwoehlke-kitware)

___
*[`.gitignore` line 36 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKfEMz5dq256iAvo0S:-NTPzt-n6C4RD9FY9crc:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/.gitignore#L36)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Minor:
</blockquote></details>

done
___
*[`cache_server/cache_logging.py` line 20 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTLEX8L7MdNNwZI-89H:-NTPzzopDdoL9gPXI_Q9:bt8b2s8) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/cache_logging.py#L20)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Can't this be expressed by a default parameter?
</blockquote></details>

done, good call, not sure why I thought it would potentially combine poorly if user also gave `kwargs` but python won't let you do that
___
*[`cache_server/disk_usage.py` line 18 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTLDkHxCBgBUQNurr_I:-NTQ02a_9DkRDW9lnscp:bx3a2qh) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/disk_usage.py#L18)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

FYI, I like `main(args: List[str])`. It's not necessary, but maybe something to consider.
</blockquote></details>

done, I do not like this and there is no need for it.
___
*[`cache_server/disk_usage.py` line 44 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTLBI6U3U67W57jiy-H:-NTQ0XaL6mRLmCxxIkCn:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/disk_usage.py#L44)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

`str` here is the default conversion, and therefore redundant. (Even if you wanted to be paranoid, `{args.mount_point!s}` would be shorter. Though, I note you omitted the `str` a bit lower. :slightly_smiling_face:)
</blockquote></details>

done
___
*[`cache_server/disk_usage.py` line 60 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTLC4vk9Ao7nvP44ee5:-NTQ0dP_4KdchrE4NARW:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/disk_usage.py#L60)):*
> ```Python
>     if du.total <= 0:
>         parser.error(
>             f"the provided mount_point='{str(args.mount_point)}' has zero total size."
> ```

done
___
*[`cache_server/disk_usage.py` line 63 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTLCKq235PPsn2JWVF9:-NTQ14JKBlmn5kz6o7EJ:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/disk_usage.py#L63)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

[Not a verb](http://www.notaverb.com/setup) :wink: 
</blockquote></details>

done
___
*[`cache_server/disk_usage.py` line 76 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTLCrMP7L0rSpjwaGuC:-NTQ346RARySZ2_-aaQn:b-bno9o5) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/disk_usage.py#L76)):*
> ```Python
>     mount_data = dedent(
>         f"""
>         - Mount: {str(args.mount_point)}
> ```

done also did GB => GiB here
___
*[`cache_server/disk_usage.py` line 88 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTLDAd-6e3SULPns71z:-NTQ3AKY6HSacRHKeuio:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/disk_usage.py#L88)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

This seems... overly excitable. :slightly_smiling_face: 
</blockquote></details>

done
___
*[`cache_server/disk_usage.py` line 100 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTLDRjc6b8lbUjlr4wU:-NTQ3IVP6uxw0gbu-tZ8:b-e0nyoz) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/disk_usage.py#L100)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I don't know if it's even worthwhile, but if this is additionally indented, will `dedent` preserve that?
</blockquote></details>

done, yes it does.  indented 4 spaces.  dedent uses left-most column


<!-- Sent from Reviewable.io -->

2023-04-19 20:13 UTC, mwoehlke-kitware reviewed
> Reviewed 1 of 3 files at r14, 3 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: 10 of 12 files reviewed, 18 unresolved discussions (waiting on @svenevs)

___
*[`cache_server/health_check.bash` line 7 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKsPZ255tP8O1f_T0b:-NTQ6qPMC7uValHmaHxI:bb6mt9b) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L7)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, we're still establishing what the actual names and arguments are :confused:
</blockquote></details>

:+1:
___
*[`cache_server/health_check.bash` line 16 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKsznYAE_EvprG29-M:-NTQ5KpuERz-3TNcJS3F:b-bvw5yi) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L16)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

why does it need to change?  grammatically `:` and then ordered list is valid
</blockquote></details>

Sorry, I think I was unclear. The colon and list are fine. "performs in order" makes "performs" 'sound like' an intransitive¹ verb, rather than a transitive verb whose object has been elided. Not eliding the object — "the script performs the following steps" — is most clear, but wordy. Simply adding a comma — "the script performs, in order" IMHO helps significantly. Otherwise I think the fragment tends to invoke the question "in order to what?".

(¹ or... something. I'm not a grammarian, I don't know what's the right name for the type of verb.)
___
*[`cache_server/health_check.bash` line 57 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKxMmmAj5zslDOBRs1:-NTQ4nEz5vbJY5QNKIGt:b53cw9a) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L57)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

done, with minor differences.  I care very little about the scenarios where things might go wrong, worst case script cannot write to there and it will fail on download.  NBD as far as we're concerned, we control the environments this runs in and can always download there.
</blockquote></details>

Sure, there's a reason I started that with 'FYI'. :slightly_smiling_face: As in, "in case you didn't know, this is what we do elsewhere; use (or don't use) this information as you see fit".

I need to remember that `-P` though, that's incredibly useful since `readlink` isn't portable!
___
*[`driver/configurations/cache.cmake` line 50 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTL-ujC0ATKw4WiwkiV:-NTQ79tG9s_xAXPxXioG:bfwf456) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/driver/configurations/cache.cmake#L50)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

done, added comma, I do not capitalize after colons ever and will not be changing any of them.  https://www.grammarly.com/blog/capitalization-after-colons/

it just depends on which format you prefer, this has no relevance in the readability or understandability
</blockquote></details>

I'm good with that.
___
*[`cache_server/disk_usage.py` line 76 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTLCrMP7L0rSpjwaGuC:-NTQ7UIH3Jzx0XttCP4P:b9uh8x8) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/disk_usage.py#L76)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

done also did GB => GiB here
</blockquote></details>

Ah, good catch, thanks!
___
*[`cache_server/disk_usage.py` line 100 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTLDRjc6b8lbUjlr4wU:-NTQ7bKY5cTdgok2G3VT:b-k7g420) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/disk_usage.py#L100)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

done, yes it does.  indented 4 spaces.  dedent uses left-most column
</blockquote></details>

Nice :+1:


<!-- Sent from Reviewable.io -->

2023-04-19 20:44 UTC, mwoehlke-kitware reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: 8 of 12 files reviewed, 12 unresolved discussions (waiting on @svenevs)

___
*[`cache_server/README.md` line 53 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh8-r2-53:-NTQB46o91UVNJF7v1qC:b-og0524) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/README.md#L53)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

done, I don't think this review comment applies to anything anymore? (stale)  there is a separate number for crontab entry
</blockquote></details>

Yup, looks stale.


<!-- Sent from Reviewable.io -->

2023-04-20 16:53 UTC, mwoehlke-kitware requested changes
> Reviewed 1 of 4 files at r15, 1 of 2 files at r17, 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: 11 of 12 files reviewed, 14 unresolved discussions (waiting on @svenevs)

___
*[`cache_server/health_check.bash` line 108 at r26](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUW8ir7Sv_noySss5x:-NTUW8ir7Sv_noySss5y:b-i33x6a) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/a0416434801c5fe4f71ff1ee64941bacc5eae9a8/cache_server/health_check.bash#L108)):*
> ```Shell
>         -o StrictHostKeyChecking=no \
>         "root@${server_ip}" \
>         'echo /cache/drake-ci/cache_server/disk_usage.py /cache/data'
> ```

Be sure to remove the `echo`! :slightly_smiling_face: (Also, `-vvv` may be overkill once we're no longer trying to figure out why it isn't working.)
___
*[`cache_server/cleanup_old_files.py` line 136 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NNdcn2cZewVLy86-xh9-r2-136:-NTUWV_i0FRi50OAadSg:b-kw4og6) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/6555e5808464b2cdb1c4efdd811f8c739ff69ec7/cache_server/cleanup_old_files.py#L136)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Possibly?  see comment above, ran it by Betsy and she agreed.  This is a safeguard against the case where pruning script starts running, but a cache job starts uploading things _after_.  It may very well be redundant based on the below:

```py
if (self.start_time - time_query) >= delta_max:
```

but I'd prefer to have the safeguard since there might be some obtuse edge case with user inputs or something?  Basically, it doesn't add much overhead and if any logic gets rearranged elsewhere it may be a problem down the line, so I would prefer to just be redundant and explicitly state "hey we don't want to delete new files being uploaded!"
</blockquote></details>

Okay. :shrug:


<!-- Sent from Reviewable.io -->

2023-04-20 17:31 UTC, mwoehlke-kitware reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: 11 of 12 files reviewed, 18 unresolved discussions (waiting on @svenevs)

___
*[`cache_server/health_check.bash` line 7 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKsPZ255tP8O1f_T0b:-NTUeBr94oU8Yozq0qfl:byaacl4) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L7)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

Reminder: mark as done from your side. :slightly_smiling_face: 
___
*[`cache_server/health_check.bash` line 4 at r29](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUeSau6v-AYGbBTR6O:-NTUeSau6v-AYGbBTR6P:b-k096p0) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/0b3689493dc2471fcd920ae39bb4190e3e02d157/cache_server/health_check.bash#L4)):*
> ```Shell
> 
> # shellcheck disable=SC2016
> doc='This script is expected to be launched by a production jenkins job so that
> ```

BTW, is there a reason why *this* needs to run on a matching arch? Or even why we need separate jobs? (I suppose separate jobs make it more obvious which server has an issue...)
___
*[`cache_server/health_check.bash` line 37 at r29](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUgW4p4KyqXoUWmOjS:-NTUgW4p4KyqXoUWmOjT:bb7lc5i) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/0b3689493dc2471fcd920ae39bb4190e3e02d157/cache_server/health_check.bash#L37)):*
> ```Shell
> 
> # Determine cache server ip address to health check based off provided name.
> # This is setup this way so that we do not have to edit the drake-jenkins-jobs
> ```

nit:



_Suggestion:_
```Shell
# Determine the cache server ip address to health check based on the provided name.
# This is set up this way so that we do not have to edit the drake-jenkins-jobs
```
___
*[`cache_server/health_check.bash` line 43 at r29](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUgfvp4XBuL1YKqUmc:-NTUgfvp4XBuL1YKqUmd:blotaje) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/0b3689493dc2471fcd920ae39bb4190e3e02d157/cache_server/health_check.bash#L43)):*
> ```Shell
> # drake-jenkins-jobs is an unnecessary maintenance burden.
> [[ $# != 1 ]] && usage
> [[ "$1" =~ ^(linux|mac-arm64)$ ]] || usage
> ```

minor: This seems redundant with the check below. (Also, this seems like a good use for `case`. :slightly_smiling_face:)

```bash
case "$server_name" in
    linux)     readonly server_ip="172.31.19.73";;
    mac-arm64) readonly server_ip="10.221.188.9";;
    *)
        echo "invalid server_name='${server_name}'" >&2
        usage()
        ;;
esac
```

___
*[`cache_server/disk_usage.py` line 88 at r29](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUfU4A1ZaFWfFIF0hb:-NTUfU4A1ZaFWfFIF0hc:bbb025j) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/0b3689493dc2471fcd920ae39bb4190e3e02d157/cache_server/disk_usage.py#L88)):*
> ```Python
>         # Simply report back to the logs everything is as expected.
>         log_message(
>             f"\n==> {percent_used}% usage is adequately beneath {args.threshold}%",
> ```

minor: (or use `round` if you prefer)



_Suggestion:_
```Python
{percent_used:.2f}
```
___
*[`cache_server/disk_usage.py` line 96 at r29](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUg1LfCd423XVaSA-W:-NTUg1LgENEfxDtvYmhZ:b5o9ztv) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/0b3689493dc2471fcd920ae39bb4190e3e02d157/cache_server/disk_usage.py#L96)):*
> ```Python
>             [X] The cache server disk usage is too high:
> 
>             {percent_used}% usage exceeds the provided threshold of {args.threshold}%!
> ```

minor: (...could probably omit changing `threshold`, though)



_Suggestion:_
```Python
{percent_used:.2f}% usage exceeds the provided threshold of {args.threshold:.2f}%
```


<!-- Sent from Reviewable.io -->

2023-04-20 20:58 UTC, svenevs reviewed
> Reviewed 1 of 1 files at r31.
> Dismissed @mwoehlke-kitware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @mwoehlke-kitware)

___
*[`cache_server/health_check.bash` line 14 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NT02wU24zC4H4j8s8Mz:-NTVLDFQAbvDnhP5Viwm:bjd30mu) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/163995cf714a3f76165259018d9b4ca5dd17013b/cache_server/health_check.bash#L14)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, some serious traumas in choosing the right values for these, answer changes depending on where you are running the script.  still identifying what ip addresses I actually need
</blockquote></details>

done, finally resolved networking issues
___
*[`cache_server/health_check.bash` line 16 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKsznYAE_EvprG29-M:-NTVLTUa2RHBt5VEAPRu:b-7z807d) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L16)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Sorry, I think I was unclear. The colon and list are fine. "performs in order" makes "performs" 'sound like' an intransitive¹ verb, rather than a transitive verb whose object has been elided. Not eliding the object — "the script performs the following steps" — is most clear, but wordy. Simply adding a comma — "the script performs, in order" IMHO helps significantly. Otherwise I think the fragment tends to invoke the question "in order to what?".

(¹ or... something. I'm not a grammarian, I don't know what's the right name for the type of verb.)
</blockquote></details>

done, added a comma after `performs`
___
*[`cache_server/health_check.bash` line 21 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKtrow5rJ_QhPaW-OH:-NTVLiUq94L5s2bzVEB6:b-3ac4ej) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L21)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Not loving the dangling preposition in (1) :slightly_smiling_face:, but nothing better is coming to mind. (Mind the suggestion in (3) if that name changes. Doesn't need to be shouty-case; the suggestion is just to use the name in some form rather than "$2".)

...["login" is not a verb](http://www.notaverb.com/login). :wink: (Didn't know about that site; neat!)
</blockquote></details>

done, this section was reworded
___
*[`cache_server/health_check.bash` line 34 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKrMOR7HE8zzDH4Xlk:-NTVLnY7-zVuIVQati1G:b-qfptd3) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L34)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, this is still being established.  $1 must be an ip address.  $2 it depends ... jenkins kinks need to be finished first
</blockquote></details>

done, script takes `linux` or `mac-arm64` now, ip is determined based off name.  so that we don't have to change jenkins yaml each time
___
*[`cache_server/health_check.bash` line 41 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKwFKI1bff0J-3Ajy3:-NTVP2g07TqkmD_lKGPd:b-jpk3i2) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L41)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, because it is probably about to change to need to run on macOS again re ip / firewall issues from jenkins
</blockquote></details>

done, this has to run on macOS in the current world order now
___
*[`cache_server/health_check.bash` line 108 at r26](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUW8ir7Sv_noySss5x:-NTVPDdK-3E6KkaDVeaw:b-7dg0dj) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/a0416434801c5fe4f71ff1ee64941bacc5eae9a8/cache_server/health_check.bash#L108)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Be sure to remove the `echo`! :slightly_smiling_face: (Also, `-vvv` may be overkill once we're no longer trying to figure out why it isn't working.)
</blockquote></details>

done, `echo` and `-vvv` gone now :slightly_smiling_face:
___
*[`cache_server/health_check.bash` line 4 at r29](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUeSau6v-AYGbBTR6O:-NTVKps3BfU2RJV1scAS:b4d1kqt) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/0b3689493dc2471fcd920ae39bb4190e3e02d157/cache_server/health_check.bash#L4)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, is there a reason why *this* needs to run on a matching arch? Or even why we need separate jobs? (I suppose separate jobs make it more obvious which server has an issue...)
</blockquote></details>

because otherwise we have to further investigate networking security blocks for the aws runners to contact that macstadium cache server.  in theory it could be solved, but it's not something I want to deal with anymore.  we wanted to do it on linux only because those runners are significantly faster to boot, but I don't know how to resolve the connection issues.  we can followup on that if we desire after this PR
___
*[`cache_server/health_check.bash` line 37 at r29](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUgW4p4KyqXoUWmOjS:-NTVMIQp1_L-n3I48Vm4:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/0b3689493dc2471fcd920ae39bb4190e3e02d157/cache_server/health_check.bash#L37)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

nit:
</blockquote></details>

done
___
*[`cache_server/health_check.bash` line 43 at r29](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUgfvp4XBuL1YKqUmc:-NTVM_PO4fTT32pQFcuu:bo734k) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/0b3689493dc2471fcd920ae39bb4190e3e02d157/cache_server/health_check.bash#L43)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

minor: This seems redundant with the check below. (Also, this seems like a good use for `case`. :slightly_smiling_face:)

```bash
case "$server_name" in
    linux)     readonly server_ip="172.31.19.73";;
    mac-arm64) readonly server_ip="10.221.188.9";;
    *)
        echo "invalid server_name='${server_name}'" >&2
        usage()
        ;;
esac
```

</blockquote></details>

done, updated `usage` to take optional argument saying why to print at end.  I kept it separately originally because I wanted the error message to show up last rather than before the wall of text that is the usage documentation.
___
*[`cache_server/disk_usage.py` line 88 at r29](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUfU4A1ZaFWfFIF0hb:-NTVKc2e-80XHMuLmU9j:bpmrbeu) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/0b3689493dc2471fcd920ae39bb4190e3e02d157/cache_server/disk_usage.py#L88)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

minor: (or use `round` if you prefer)
</blockquote></details>

done, good call
___
*[`cache_server/disk_usage.py` line 96 at r29](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUg1LfCd423XVaSA-W:-NTVKe-rC0yFGs9T56Fn:ba8wcwh) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/0b3689493dc2471fcd920ae39bb4190e3e02d157/cache_server/disk_usage.py#L96)):*
<details><summary><i>Previous [...]

2023-04-20 21:34 UTC, svenevs reviewed
ok, everything has been re-unified, each server is up to date with this PR.  cache check jobs work as expected:

- https://drake-jenkins.csail.mit.edu/view/Cache%20Server/job/linux-cache-server-health-check/29/consoleFull
- https://drake-jenkins.csail.mit.edu/view/Cache%20Server/job/mac-arm64-cache-server-health-check/12/consoleFull

I added a new section a the bottom of the readme with the instructions for how to do the clean up manually.  We may need to truncate linux clean up window to 1.5 days, continuous debug seems to add quite a lot.

Those jobs cannot become production jobs until this PR is merged to `main` (aka I'll follow that up)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-:-NTV_OK7ARmc4I1QOL72:b336z6i)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @mwoehlke-kitware)



<!-- Sent from Reviewable.io -->

2023-04-21 19:15 UTC, mwoehlke-kitware reviewed
Okay, I'm going to give this a <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>. There are exactly three minor, but non-blocking comments in README and remove_old_files, and one is just a request for personal edification.

> Reviewed 2 of 3 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-:-NT_E9tUEdQicQ_jmjC0:b-wrdb8r)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @svenevs)

___
*[`cache_server/health_check.bash` line 16 at r13](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTKsznYAE_EvprG29-M:-NT_5e3qCTxRjW6dp1GE:b-9755fn) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e4f2fb02816d9547e4c01ed9b444e20a82b78bfe/cache_server/health_check.bash#L16)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

done, added a comma after `performs`
</blockquote></details>

Thank you!
___
*[`cache_server/health_check.bash` line 4 at r29](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUeSau6v-AYGbBTR6O:-NT_5XK9B4MV8TYQfzzx:b8qkmgw) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/0b3689493dc2471fcd920ae39bb4190e3e02d157/cache_server/health_check.bash#L4)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

because otherwise we have to further investigate networking security blocks for the aws runners to contact that macstadium cache server.  in theory it could be solved, but it's not something I want to deal with anymore.  we wanted to do it on linux only because those runners are significantly faster to boot, but I don't know how to resolve the connection issues.  we can followup on that if we desire after this PR
</blockquote></details>

As Homer would say.. d'oh! :flushed:
___
*[`cache_server/health_check.bash` line 43 at r29](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTUgfvp4XBuL1YKqUmc:-NT_DI6JB3IDfvMBeJQ2:b-y8yjll) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/0b3689493dc2471fcd920ae39bb4190e3e02d157/cache_server/health_check.bash#L43)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

done, updated `usage` to take optional argument saying why to print at end.  I kept it separately originally because I wanted the error message to show up last rather than before the wall of text that is the usage documentation.
</blockquote></details>

Ah, makes sense. I like the change, though; good idea!
___
*[`cache_server/README.md` line 278 at r34](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NT_68kp0OLhH0DQUNfE:-NT_68kp0OLhH0DQUNfF:b-nhn7o6) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/a2f9053bb16cc48130c92336b0227685402f440c/cache_server/README.md#L278)):*
> ```Markdown
> 
> In the event that the `cron` jobs running
> [`remove_old_files.py`](./remove_old_files.py) is not removing enough disk space
> ```

minor:



_Suggestion:_
```Markdown
are not freeing enough disk space,
```
___
*[`cache_server/README.md` line 280 at r34](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NT_6QNZ606lDNvAbQjA:-NT_6QNZ606lDNvAbQjB:b4fzti7) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/a2f9053bb16cc48130c92336b0227685402f440c/cache_server/README.md#L280)):*
> ```Markdown
> [`remove_old_files.py`](./remove_old_files.py) is not removing enough disk space
> the monitoring jobs in the previous section will start notifying the buildcops.
> You must log in to the cache server in question and run the script manually with
> ```

Do we expect this to be a one-time event? (As opposed to needing to either grow the storage or reduce the retention time specified in the cron job(s)?)
___
*[`cache_server/remove_old_files.py` line 104 at r24](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTQMQEn5wUBd1vh4Civ:-NT_7Afn-lgo1oNlKS83:b-efe744) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/f3b69929fa55cd622e1c6270ea876504eabd9e00/cache_server/remove_old_files.py#L104)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

not quite, they are disabled.  the `def func_name(*, ...)` syntax means anything after `*,` must be a named parameter.  forces call-site to be more descriptive.  it's not a deal breaker to me either way, I don't see a reason to remove it, or keep it, I just generally tend to prefer using keyword args
</blockquote></details>

Huh, I did not know that. TIL. :slightly_smiling_face: 
___
*[`cache_server/remove_old_files.py` line 201 at r24](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTQXI4a94KFlxibCGrt:-NT_7a3mAJvxGxAutQqI:bc52tdo) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/f3b69929fa55cd622e1c6270ea876504eabd9e00/cache_server/remove_old_files.py#L201)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

done, good eye! the readbale is where you bale up all your books and read them?
</blockquote></details>

:laughing: 
___
*[`cache_server/remove_old_files.py` line 214 at r24](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTQ_ukq4sAx7GiegA08:-NT_7wYQDVIfO1X4s1M4:b-ot18fv) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/f3b69929fa55cd622e1c6270ea876504eabd9e00/cache_server/remove_old_files.py#L214)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

you'd need to compute a percentile to determine "every so many files" anyway.  In manually running the script, I find the percent indicator adequate -- when deleting close to 150GB just now it gives me an indicator that things are moving, and the script is fast enough that it works for its purpose (indicate to user "I am working still")

if there's nothing specific you have in mind I'd rather leave it for no other reason than "it's good enough"
</blockquote></details>

I meant something like this:
```python
if (i % 1000) == 0:
    log_message(f"Deleting... {i} of {n_files}")
```

Note that `1000` is a *constant* value, not computed. This means if there's very little to do, you get few (or no) reports, while if there's a *lot* to do, you get more reports... but the wall-time interval *between* reports should be roughly constant. (Or at least, not directly dependent on the total number of files.)

You could, if you prefer, easily tweak the above to report a percentage rather than a raw "X of Y", but it sounds like that's unnecessary.


<!-- Sent from Reviewable.io -->

2023-04-25 09:14 UTC, svenevs reviewed
ok, made the last round of changes + removed the `-s` from `cron` entry prototype instructions (we removed `-s` from `remove_old_files`...) as well as fixed the logrotate config.  should be good to go now, pending review of reworded sections.  Thanks!

> Reviewed 2 of 3 files at r32, 1 of 1 files at r34, 3 of 3 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-:-NTrg7UIAChpJPAEYJeD:b-dz50g3)* status: all files reviewed, 1 unresolved discussion (waiting on @mwoehlke-kitware)

___
*[`cache_server/logrotate_cache.conf` line 4 at r35](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTrfo-B29KAfRzX_Gf7:-NTrfo-B29KAfRzX_Gf8:bc00652) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/d638b2b07f5928e6963fa560a97af96ebcd7bef1/cache_server/logrotate_cache.conf#L4)):*
> ```
> # Logs will be rotated 10 times and then deleted.
> # Note that the cron job running this is expected to execute daily.
> "/cache/log/*.log" "/cache/log/nginx/*.log" {
> ```

fyi this was a bad config, nginx logs didn't get rotated but now they will be
___
*[`cache_server/README.md` line 278 at r34](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NT_68kp0OLhH0DQUNfE:-NTrYzCJ7MejeA3IIdAi:b-tbwfxv) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/a2f9053bb16cc48130c92336b0227685402f440c/cache_server/README.md#L278)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

minor:
</blockquote></details>

done ish, changed to `cron job running`, there's only one, so made it singular.  wordwrapping is the rest of that diff
___
*[`cache_server/README.md` line 280 at r34](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NT_6QNZ606lDNvAbQjA:-NTrZDHn1gci7kbty00p:bi21tn6) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/a2f9053bb16cc48130c92336b0227685402f440c/cache_server/README.md#L280)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Do we expect this to be a one-time event? (As opposed to needing to either grow the storage or reduce the retention time specified in the cron job(s)?)
</blockquote></details>

this would more or less be the protocol to follow to determine what to do.  I added a sentence at the end to help explain that whoever is doing this manually likely has a followup action.  officially there is one more option: reduce # of jobs populating this cache server.  please review final sentence and confirm this is clear now, thanks for clarifying!
___
*[`cache_server/remove_old_files.py` line 214 at r24](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTQ_ukq4sAx7GiegA08:-NTrcvVm0Ks7Et8QdNp8:bfa214d) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/f3b69929fa55cd622e1c6270ea876504eabd9e00/cache_server/remove_old_files.py#L214)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I meant something like this:
```python
if (i % 1000) == 0:
    log_message(f"Deleting... {i} of {n_files}")
```

Note that `1000` is a *constant* value, not computed. This means if there's very little to do, you get few (or no) reports, while if there's a *lot* to do, you get more reports... but the wall-time interval *between* reports should be roughly constant. (Or at least, not directly dependent on the total number of files.)

You could, if you prefer, easily tweak the above to report a percentage rather than a raw "X of Y", but it sounds like that's unnecessary.
</blockquote></details>

done, this is not a good change, on the cache server that will flood the logs (last run had `255504` files removed, that number varies _widely_ between the servers).  we are balancing having useful logging (the higher priority) with also making manual user runs more apparent that they are still going rather than thinking it has changed.  i incorporated part of your request, the log will now look like this (using a small test sample on my local drive)

```
2023-04-25 05:09:00 :: ================================================================================
2023-04-25 05:09:00 :: Age strategy:   TimeMetric.ACCESS_TIME
2023-04-25 05:09:00 :: Time delta max: 0:00:01
2023-04-25 05:09:00 :: ==> /cache
2023-04-25 05:09:00 :: Found: 1115 total files.
2023-04-25 05:09:00 :: 1115 file(s) eligible for pruning.
2023-04-25 05:09:00 :: 1.69 GiB disk space eligible for pruning.
2023-04-25 05:09:00 :: Removing file [   1 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 113 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 225 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 337 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 449 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 561 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 673 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 785 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 897 / 1115] ...
2023-04-25 05:09:00 :: Removing file [1009 / 1115] ...
2023-04-25 05:09:00 :: DONE.
```

it takes a constant amount of space for each entry, it's well formatted.  it is good enough, anybody running it on the production server will get the immediate notification of it doing something

removed percent indication, but kept it printing at ~10% intervals


<!-- Sent from Reviewable.io -->

2023-04-25 14:44 UTC, mwoehlke-kitware approved these changes
> Reviewed 1 of 3 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: all files reviewed, 2 unresolved discussions (waiting on @svenevs)

___
*[`cache_server/README.md` line 278 at r34](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NT_68kp0OLhH0DQUNfE:-NTsk4rB5FdMcjgWkKz4:bk25p0q) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/a2f9053bb16cc48130c92336b0227685402f440c/cache_server/README.md#L278)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

done ish, changed to `cron job running`, there's only one, so made it singular.  wordwrapping is the rest of that diff
</blockquote></details>

D'oh, you're right, of course. :slightly_smiling_face: Anyway, much better now, thanks!
___
*[`cache_server/README.md` line 280 at r34](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NT_6QNZ606lDNvAbQjA:-NTsr3KCE-OVJ16pE0yU:bf6isno) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/a2f9053bb16cc48130c92336b0227685402f440c/cache_server/README.md#L280)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

this would more or less be the protocol to follow to determine what to do.  I added a sentence at the end to help explain that whoever is doing this manually likely has a followup action.  officially there is one more option: reduce # of jobs populating this cache server.  please review final sentence and confirm this is clear now, thanks for clarifying!
</blockquote></details>

Okay, makes more sense with that addition, thanks!
___
*[`cache_server/README.md` line 300 at r35](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTskNJNCFazUklVUVgl:-NTskNJNCFazUklVUVgm:bq6gd8h) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/d638b2b07f5928e6963fa560a97af96ebcd7bef1/cache_server/README.md#L300)):*
> ```Markdown
> Depending on how much disk space you need to free up, anything longer than 1.5
> days (`--days 1 --hours 12`) should be safe to delete immediately.  For a given
> cache server, if this happens multiple times then one of three updates must be
> ```

minor: "updates" is a little odd here. Maybe "three options must be chosen", or "three changes must be applied", or something along those lines.

I probably wouldn't bother leaving a comment at this point, except... (con't)
___
*[`cache_server/README.md` line 303 at r35](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTskfVd8MGL_ZGAhygV:-NTskfVd8MGL_ZGAhygW:bxy5un5) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/d638b2b07f5928e6963fa560a97af96ebcd7bef1/cache_server/README.md#L303)):*
> ```Markdown
> chosen:
> 
> - Update the time interval for the `cron` job running
> ```

minor: (con't) ...this sentence is quite oddly worded (a la "department of redundancy department"); one of "Update ..." or "... should be updated" should probably be removed.
___
*[`cache_server/remove_old_files.py` line 214 at r24](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-NTQ_ukq4sAx7GiegA08:-NTslMs70szEXYT-9tQN:b-9i8ym9) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/f3b69929fa55cd622e1c6270ea876504eabd9e00/cache_server/remove_old_files.py#L214)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

done, this is not a good change, on the cache server that will flood the logs (last run had `255504` files removed, that number varies _widely_ between the servers).  we are balancing having useful logging (the higher priority) with also making manual user runs more apparent that they are still going rather than thinking it has changed.  i incorporated part of your request, the log will now look like this (using a small test sample on my local drive)

```
2023-04-25 05:09:00 :: ================================================================================
2023-04-25 05:09:00 :: Age strategy:   TimeMetric.ACCESS_TIME
2023-04-25 05:09:00 :: Time delta max: 0:00:01
2023-04-25 05:09:00 :: ==> /cache
2023-04-25 05:09:00 :: Found: 1115 total files.
2023-04-25 05:09:00 :: 1115 file(s) eligible for pruning.
2023-04-25 05:09:00 :: 1.69 GiB disk space eligible for pruning.
2023-04-25 05:09:00 :: Removing file [   1 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 113 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 225 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 337 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 449 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 561 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 673 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 785 / 1115] ...
2023-04-25 05:09:00 :: Removing file [ 897 / 1115] ...
2023-04-25 05:09:00 :: Removing file [1009 / 1115] ...
2023-04-25 05:09:00 :: DONE.
```

it takes a constant amount of space for each entry, it's well formatted.  it is good enough, anybody running it on the production server will get the immediate notification of it doing something

removed percent indication, but kept it printing at ~10% intervals
</blockquote></details>

The goal was to not appear to go out for tea if it needs to remove, say, 20M files. (Okay, maybe that would never happen.) From the above log, I would say it's clear that every 1k is too often; maybe every 10k, 20k or even 50k would be more appropriate. Many updates per second is unnecessary, but going more than ~10 seconds with no progress indicator is sub-optimal.

OTOH, maybe we *should* print every 1k... and also use carriage-returns to re-use the line, *and only show progress on a tty*? It seems you are arguing that progress is only useful for manual runs, which seems entirely reasonable.

(Another option would be to print 'Removing N files ...' followed by a single additional '.' for every ~1k or even 10k. But that probably doesn't work nicely with the logging.)

BTW, that formatting is very nice. :+1:


<!-- Sent from Reviewable.io -->

2023-04-25 20:34 UTC, svenevs reviewed
> Reviewed 1 of 1 files at r37, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @svenevs)



<!-- Sent from Reviewable.io -->

2023-04-26 15:06 UTC, mwoehlke-kitware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/198#-:-NTy5P0VBsbXlL7VFmGv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @svenevs)



<!-- Sent from Reviewable.io -->

2023-04-26 19:37 UTC, merged