[cache] Fix file removal strategy
RobotLocomotion/drake-ci pull request #222
Opened 2023-05-05 04:10 UTC by svenevs

- remove_old_files.py:
    - Change defaults from 4 to 2 days.
    - Add `auto` strategy that starts searching at 2 days, decreasing by 2 hours until a time metric that would result in the provided disk utilization percentage (default: 70%) **or lower**.  The search strategy is not intelligent, and two hours (depending on the day) can mean anything between 2% or 20%.  For example, searching for 70% or lower can result in utilization being 50%.
    - Original behavior is now behind the `manual` strategy. Allowed arguments reduced to days, hours, and minutes.
    - Rename / reorganize various methods to support the new strategies.
- README.md:
    - Update infrastructure skeleton to clone drake-ci to `/root` to avoid issues where when `/cache` is full you cannot `git pull`.
    - Change `cron` schedules to remove files and monitor more aggressively.

2023-05-05 04:22 UTC, svenevs reviewed
+@BetsyMcPhail for review of most of the skeleton changes here to add `auto` mode.  Thread on fine tuning below open for discussion.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-:-NUe8DLZB5ctw_J6_n0G:bng9p7i)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @BetsyMcPhail and @svenevs)

___
*[`cache_server/remove_old_files.py` line 436 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUe64VT6aRgBxsz2zi_:-NUe64VT6aRgBxsz2zia:bskfcra) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b732e60161d2a613a6ab34115d39df4fc181f8f1/cache_server/remove_old_files.py#L436)):*
> ```Python
>                 log_message(f"==> would achieve {round(current_percent_used, 2)}%")
> 
>                 delta_max -= timedelta(hours=2)
> ```

working, scrapped this together in the evening while cache server was full but before nightlies (staging the cache too full scenario locally is tedious).  I think the logic is close, needs some more thought now that we have data.  See also proposed new `cron` schedules (to discuss in one thread here):


However, two hours decrease can actually have some extreme results.  First production run of the `auto` mode searched for 70 and brought it down to 48% (OK, I knew nightlies were about to launch).

```
2023-05-05 00:07:25 :: ================================================================================
2023-05-05 00:07:25 :: Age strategy:   TimeMetric.ACCESS_TIME
2023-05-05 00:07:25 :: Time delta max: 2 days, 0:00:00
2023-05-05 00:07:25 :: NOTE: dry run, (no files will be removed).
2023-05-05 00:07:27 :: ==> /cache/data
2023-05-05 00:07:27 :: Found: 220925 total files.
2023-05-05 00:07:27 ::        465.93 GiB total data.
2023-05-05 00:07:27 :: Scanning for timedelta to achieve <= 30.0% utilization:
2023-05-05 00:07:27 :: 2 days, 0:00:00:
2023-05-05 00:07:27 :: Found: 0 file(s) to remove.
2023-05-05 00:07:27 ::        0 Bytes disk space eligible for removal.
2023-05-05 00:07:27 :: ==> would achieve 48.1%
...
2023-05-05 00:07:28 :: ==> would achieve 48.1%
2023-05-05 00:07:28 :: 12:00:00:
2023-05-05 00:07:28 :: Found: 0 file(s) to remove.
2023-05-05 00:07:28 ::        0 Bytes disk space eligible for removal.
2023-05-05 00:07:28 :: ==> would achieve 48.1%
2023-05-05 00:07:28 :: 10:00:00:
2023-05-05 00:07:28 :: Found: 7086 file(s) to remove.
2023-05-05 00:07:28 ::        50.76 GiB disk space eligible for removal.
2023-05-05 00:07:28 :: ==> would achieve 43.02%
2023-05-05 00:07:28 :: 8:00:00:
2023-05-05 00:07:28 :: Found: 152470 file(s) to remove.
2023-05-05 00:07:28 ::        412.82 GiB disk space eligible for removal.
2023-05-05 00:07:28 :: ==> would achieve 6.8%
2023-05-05 00:07:28 :: DONE: 6:00:00
```

Thoughts:

- Decrease search window decrement to say, 15 or 30 minutes?  2 hours can result in something quite dramatic.
- Put more safety guards in -- right now allowed threshold is between 1 and 99%, probably I can easily just track the previous delta_max and if it's going to go too far (who knows, 15 minutes may even do that)

Overall I think this is really close to being a smooth solution, just need to tighten some gaps.
___
*[`cache_server/remove_old_files.py` line 438 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUe84FA5gGM1Dy397S6:-NUe84FA5gGM1Dy397S7:b-rudra1) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b732e60161d2a613a6ab34115d39df4fc181f8f1/cache_server/remove_old_files.py#L438)):*
> ```Python
>                 delta_max -= timedelta(hours=2)
> 
>             log_message(f"DONE: {delta_max}")
> ```

working, in log above it's saying DONE at 6:00 but it should be 8:00 (while loop decrement).  just delete this


<!-- Sent from Reviewable.io -->

2023-05-05 04:28 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @BetsyMcPhail)

___
*[`cache_server/remove_old_files.py` line 436 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUe64VT6aRgBxsz2zi_:-NUe9MKF-3AGgpwR4GBK:b-gdgxgk) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b732e60161d2a613a6ab34115d39df4fc181f8f1/cache_server/remove_old_files.py#L436)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, scrapped this together in the evening while cache server was full but before nightlies (staging the cache too full scenario locally is tedious).  I think the logic is close, needs some more thought now that we have data.  See also proposed new `cron` schedules (to discuss in one thread here):


However, two hours decrease can actually have some extreme results.  First production run of the `auto` mode searched for 70 and brought it down to 48% (OK, I knew nightlies were about to launch).

```
2023-05-05 00:07:25 :: ================================================================================
2023-05-05 00:07:25 :: Age strategy:   TimeMetric.ACCESS_TIME
2023-05-05 00:07:25 :: Time delta max: 2 days, 0:00:00
2023-05-05 00:07:25 :: NOTE: dry run, (no files will be removed).
2023-05-05 00:07:27 :: ==> /cache/data
2023-05-05 00:07:27 :: Found: 220925 total files.
2023-05-05 00:07:27 ::        465.93 GiB total data.
2023-05-05 00:07:27 :: Scanning for timedelta to achieve <= 30.0% utilization:
2023-05-05 00:07:27 :: 2 days, 0:00:00:
2023-05-05 00:07:27 :: Found: 0 file(s) to remove.
2023-05-05 00:07:27 ::        0 Bytes disk space eligible for removal.
2023-05-05 00:07:27 :: ==> would achieve 48.1%
...
2023-05-05 00:07:28 :: ==> would achieve 48.1%
2023-05-05 00:07:28 :: 12:00:00:
2023-05-05 00:07:28 :: Found: 0 file(s) to remove.
2023-05-05 00:07:28 ::        0 Bytes disk space eligible for removal.
2023-05-05 00:07:28 :: ==> would achieve 48.1%
2023-05-05 00:07:28 :: 10:00:00:
2023-05-05 00:07:28 :: Found: 7086 file(s) to remove.
2023-05-05 00:07:28 ::        50.76 GiB disk space eligible for removal.
2023-05-05 00:07:28 :: ==> would achieve 43.02%
2023-05-05 00:07:28 :: 8:00:00:
2023-05-05 00:07:28 :: Found: 152470 file(s) to remove.
2023-05-05 00:07:28 ::        412.82 GiB disk space eligible for removal.
2023-05-05 00:07:28 :: ==> would achieve 6.8%
2023-05-05 00:07:28 :: DONE: 6:00:00
```

Thoughts:

- Decrease search window decrement to say, 15 or 30 minutes?  2 hours can result in something quite dramatic.
- Put more safety guards in -- right now allowed threshold is between 1 and 99%, probably I can easily just track the previous delta_max and if it's going to go too far (who knows, 15 minutes may even do that)

Overall I think this is really close to being a smooth solution, just need to tighten some gaps.
</blockquote></details>

Sorry, the hypothesized new cron schedule:

- remove old files: every hour at minute 0 between 8am and 10pm
- disk usage logging: every hour at minute 30 between 8am and 10pm
- TBD: jenkins continuous cache check.  We could remove the cron for disk usage logging and just run this for our logging instead
- rotate logs: 7am


<!-- Sent from Reviewable.io -->

2023-05-05 07:07 UTC, svenevs reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @BetsyMcPhail)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUehPW410t0lcl0r0YT):*
working, reduce after discussion, this was taking notes while rebasing
___
*[`cache_server/README.md` line 73 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUehUXD312S6n1bNa_I:-NUehUXD312S6n1bNa_J:b-d03nvz) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b732e60161d2a613a6ab34115d39df4fc181f8f1/cache_server/README.md#L73)):*
> ```Markdown
> 
> - Cache data storage volumes are mounted to `/cache`.
> - This repository should be cloned to `/root/drake-ci`.  Do not put it on the
> ```

working, I don't think `/root/drake-ci` is the right location.  Before moving again, on AWS we have an 8GB `/` volume, on mac side a 20GB `/` volume.

I think it would make sense to make `/opt/drake-ci` and `/opt/log`.  The idea is to safeguard against any future mishaps where we don't know something is wrong until the cache is full (for whatever reason).  Right now developing via `git` is an issue in `drake-ci` (reason for original diff here), but in hindsight this also means that we lose all logging for nginx and other tooling.  So move those to somewhere safe under `/` volume (not `/cache`).


<!-- Sent from Reviewable.io -->

2023-05-05 20:04 UTC, BetsyMcPhail submitted a review, later dismissed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222)* status: all files reviewed, 5 unresolved discussions (waiting on @svenevs)

___
*[`cache_server/README.md` line 73 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUehUXD312S6n1bNa_I:-NUgtdkECZjlopixIlTW:b28j87i) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b732e60161d2a613a6ab34115d39df4fc181f8f1/cache_server/README.md#L73)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, I don't think `/root/drake-ci` is the right location.  Before moving again, on AWS we have an 8GB `/` volume, on mac side a 20GB `/` volume.

I think it would make sense to make `/opt/drake-ci` and `/opt/log`.  The idea is to safeguard against any future mishaps where we don't know something is wrong until the cache is full (for whatever reason).  Right now developing via `git` is an issue in `drake-ci` (reason for original diff here), but in hindsight this also means that we lose all logging for nginx and other tooling.  So move those to somewhere safe under `/` volume (not `/cache`).
</blockquote></details>

I don't follow all of the details here, but I agree we shouldn't be using /root.
___
*[`cache_server/remove_old_files.py` line 18 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUhJwK79zMFQeQcgIC_:-NUhJwK79zMFQeQcgICa:b-nvsffc) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b732e60161d2a613a6ab34115d39df4fc181f8f1/cache_server/remove_old_files.py#L18)):*
> ```Python
>     The default for days is always 2.  If you desire to delete all files that have not
>     been accessed within the last 5 hours, for example, you should supply both
>     ``--days 0`` and ``--hours 5``.  Providing just `--hours 5`` will result in four
> ```

Nit missed a "four" --> "two"
___
*[`cache_server/remove_old_files.py` line 436 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUe64VT6aRgBxsz2zi_:-NUhTzYv4CD6Rvg0UpPH:b-ylcn23) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b732e60161d2a613a6ab34115d39df4fc181f8f1/cache_server/remove_old_files.py#L436)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Sorry, the hypothesized new cron schedule:

- remove old files: every hour at minute 0 between 8am and 10pm
- disk usage logging: every hour at minute 30 between 8am and 10pm
- TBD: jenkins continuous cache check.  We could remove the cron for disk usage logging and just run this for our logging instead
- rotate logs: 7am
</blockquote></details>

I'm concerned that implementing anything that is too "smart" here will end up being complicated and require maintenance. If decreasing the search window is simple and good enough, I don't think a lot will be gained by further checks.


<!-- Sent from Reviewable.io -->

2023-05-06 04:10 UTC, svenevs reviewed
ok, seems close, confirmed logging updates are OK for both nginx and logrotate conf.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-:-NUjEiEo4E43t1XBExEK:bpzb92a)* status: all files reviewed, 2 unresolved discussions (waiting on @svenevs)

___
*[`cache_server/health_check.bash` line 116 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUjCgM93SnDJVCXfl-9:-NUjCgMACsdCN1eOIUBF:bqdfj54) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/950d775c0c6d1a2ca4822420648a28b19ff58c84/cache_server/health_check.bash#L116)):*
> ```Shell
>         -i "${cache_server_id_rsa_path}" \
>         "root@${server_ip}" \
>         '/opt/cache_server/drake-ci/cache_server/disk_usage.py /cache/data'
> ```

working, before this merges / once we are finalized on linux server, I need to re-bootstrap the mac server

sorry for all the noise with the pushing, easiest way to develop this thing is to just work with the live data, but I wanted to also make sure that the README instructions can be copy pasted to make a new one (verify steps for start to finish)
___
*[`cache_server/README.md` line 73 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUehUXD312S6n1bNa_I:-NUjD47h32xcFl5xi68P:b7o6nnh) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b732e60161d2a613a6ab34115d39df4fc181f8f1/cache_server/README.md#L73)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

I don't follow all of the details here, but I agree we shouldn't be using /root.
</blockquote></details>

done, moved things to `/opt/cache_server`, tried adding some clarifications in relevant locations, TLDR it shouldn't live on `/cache` since if that is full no disk write operations can happen

it would be appreciated if you can quickly re-skim the diff on the README, but the rest of the tools I think I got the updates
___
*[`cache_server/remove_old_files.py` line 18 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUhJwK79zMFQeQcgIC_:-NUisTmh7GXFPMLgy9Bs:b67defc) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b732e60161d2a613a6ab34115d39df4fc181f8f1/cache_server/remove_old_files.py#L18)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Nit missed a "four" --> "two"
</blockquote></details>

done, thanks!  I rewrote / tried to simplify the main docs, it was outdated
___
*[`cache_server/remove_old_files.py` line 436 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUe64VT6aRgBxsz2zi_:-NUjDbWZ5hEo0LB7YJ5f:bwanktx) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b732e60161d2a613a6ab34115d39df4fc181f8f1/cache_server/remove_old_files.py#L436)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

I'm concerned that implementing anything that is too "smart" here will end up being complicated and require maintenance. If decreasing the search window is simple and good enough, I don't think a lot will be gained by further checks.
</blockquote></details>

absolutely agreed, this script is already confusing to reason about.  Reducing to 15 minute search window seems like an OK choice right now.  We will want to collect data Monday and Tuesday while things are merging on drake, maybe make the search window smaller but it seems OK to me.  Sample output from today:

```
2023-05-05 23:25:42 :: ================================================================================
2023-05-05 23:25:42 :: Age strategy:   TimeMetric.ACCESS_TIME
2023-05-05 23:25:42 :: Time delta max: 2 days, 0:00:00
2023-05-05 23:25:49 :: ==> /cache/data
2023-05-05 23:25:49 :: Scanning for timedelta to achieve <= 70.0% utilization:
2023-05-05 23:25:49 :: Delta: 2 days, 0:00:00 => 0 file(s), 0 Bytes eligbile for removal
...
2023-05-05 23:25:53 :: Delta: 1 day, 9:45:00 => 0 file(s), 0 Bytes eligbile for removal
2023-05-05 23:25:53 :: Delta: 1 day, 9:30:00 => 1846 file(s), 13.11 GiB eligbile for removal
2023-05-05 23:25:53 :: Delta: 1 day, 9:15:00 => 9128 file(s), 82.28 GiB eligbile for removal
2023-05-05 23:25:53 :: Delta: 1 day, 9:00:00 => 23969 file(s), 151.28 GiB eligbile for removal
2023-05-05 23:25:53 :: Found: 536548 total files.
2023-05-05 23:25:53 ::        816.39 GiB total data.
2023-05-05 23:25:53 :: Found: 23969 file(s) to remove.
2023-05-05 23:25:53 ::        151.28 GiB disk space eligible for removal.
2023-05-05 23:25:53 :: Removing file [    1 / 23969] ...
2023-05-05 23:25:53 :: Removing file [ 2398 / 23969] ...
2023-05-05 23:25:53 :: Removing file [ 4795 / 23969] ...
2023-05-05 23:25:53 :: Removing file [ 7192 / 23969] ...
2023-05-05 23:25:53 :: Removing file [ 9589 / 23969] ...
2023-05-05 23:25:53 :: Removing file [11986 / 23969] ...
2023-05-05 23:25:53 :: Removing file [14383 / 23969] ...
2023-05-05 23:25:53 :: Removing file [16780 / 23969] ...
2023-05-05 23:25:53 :: Removing file [19177 / 23969] ...
2023-05-05 23:25:53 :: Removing file [21574 / 23969] ...
2023-05-05 23:25:53 :: DONE.
```

Subsequent run:

```
2023-05-05 23:58:18 :: ================================================================================
2023-05-05 23:58:18 :: Age strategy:   TimeMetric.ACCESS_TIME
2023-05-05 23:58:18 :: Time delta max: 2 days, 0:00:00
2023-05-05 23:58:24 :: Disk usage for /cache/data is currently at 68.2%,
2023-05-05 23:58:24 :: which is beneath the requested threshold of 70.0.
2023-05-05 23:58:24 :: No files to remove.
```

Cron schedules still plan to run  interleaved every 30 minutes, will check in on that next week
___
*[`cache_server/remove_old_files.py` line 438 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUe84FA5gGM1Dy397S6:-NUjEdvq3dSUuX2fKTR_:bdek3t1) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b732e60161d2a613a6ab34115d39df4fc181f8f1/cache_server/remove_old_files.py#L438)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, in log above it's saying DONE at 6:00 but it should be 8:00 (while loop decrement).  just delete this
</blockquote></details>

done, removed


<!-- Sent from Reviewable.io -->

2023-05-08 17:25 UTC, BetsyMcPhail requested changes
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222)* status: all files reviewed, 3 unresolved discussions (waiting on @svenevs)

___
*[`cache_server/README.md` line 303 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUwNnAE6K_LU9fKh0I7:-NUwNnAE6K_LU9fKh0I8:bs5cuqe) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/08ab6efc3f5e8b6510a255fc3a9413c2e013c5aa/cache_server/README.md#L303)):*
> ```Markdown
> 
> ```console
> /opt/drake-ci/cache_server/remove_old_files.py -n auto -t 60 /cache/data/
> ```

Here and the next three instances below should be /opt/cache_server/drake-ci/...


<!-- Sent from Reviewable.io -->

2023-05-10 14:03 UTC, svenevs reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @BetsyMcPhail)

___
*[`cache_server/README.md` line 303 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUwNnAE6K_LU9fKh0I7:-NV4y8BY-QkIhZeKZarR:b-oq282j) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/08ab6efc3f5e8b6510a255fc3a9413c2e013c5aa/cache_server/README.md#L303)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Here and the next three instances below should be /opt/cache_server/drake-ci/...
</blockquote></details>

done, good catch -- thanks!
___
*[`cache_server/remove_old_files.py` line 436 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUe64VT6aRgBxsz2zi_:-NV4yAsn2703E75vCf67:b-j97sr1) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b732e60161d2a613a6ab34115d39df4fc181f8f1/cache_server/remove_old_files.py#L436)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

absolutely agreed, this script is already confusing to reason about.  Reducing to 15 minute search window seems like an OK choice right now.  We will want to collect data Monday and Tuesday while things are merging on drake, maybe make the search window smaller but it seems OK to me.  Sample output from today:

```
2023-05-05 23:25:42 :: ================================================================================
2023-05-05 23:25:42 :: Age strategy:   TimeMetric.ACCESS_TIME
2023-05-05 23:25:42 :: Time delta max: 2 days, 0:00:00
2023-05-05 23:25:49 :: ==> /cache/data
2023-05-05 23:25:49 :: Scanning for timedelta to achieve <= 70.0% utilization:
2023-05-05 23:25:49 :: Delta: 2 days, 0:00:00 => 0 file(s), 0 Bytes eligbile for removal
...
2023-05-05 23:25:53 :: Delta: 1 day, 9:45:00 => 0 file(s), 0 Bytes eligbile for removal
2023-05-05 23:25:53 :: Delta: 1 day, 9:30:00 => 1846 file(s), 13.11 GiB eligbile for removal
2023-05-05 23:25:53 :: Delta: 1 day, 9:15:00 => 9128 file(s), 82.28 GiB eligbile for removal
2023-05-05 23:25:53 :: Delta: 1 day, 9:00:00 => 23969 file(s), 151.28 GiB eligbile for removal
2023-05-05 23:25:53 :: Found: 536548 total files.
2023-05-05 23:25:53 ::        816.39 GiB total data.
2023-05-05 23:25:53 :: Found: 23969 file(s) to remove.
2023-05-05 23:25:53 ::        151.28 GiB disk space eligible for removal.
2023-05-05 23:25:53 :: Removing file [    1 / 23969] ...
2023-05-05 23:25:53 :: Removing file [ 2398 / 23969] ...
2023-05-05 23:25:53 :: Removing file [ 4795 / 23969] ...
2023-05-05 23:25:53 :: Removing file [ 7192 / 23969] ...
2023-05-05 23:25:53 :: Removing file [ 9589 / 23969] ...
2023-05-05 23:25:53 :: Removing file [11986 / 23969] ...
2023-05-05 23:25:53 :: Removing file [14383 / 23969] ...
2023-05-05 23:25:53 :: Removing file [16780 / 23969] ...
2023-05-05 23:25:53 :: Removing file [19177 / 23969] ...
2023-05-05 23:25:53 :: Removing file [21574 / 23969] ...
2023-05-05 23:25:53 :: DONE.
```

Subsequent run:

```
2023-05-05 23:58:18 :: ================================================================================
2023-05-05 23:58:18 :: Age strategy:   TimeMetric.ACCESS_TIME
2023-05-05 23:58:18 :: Time delta max: 2 days, 0:00:00
2023-05-05 23:58:24 :: Disk usage for /cache/data is currently at 68.2%,
2023-05-05 23:58:24 :: which is beneath the requested threshold of 70.0.
2023-05-05 23:58:24 :: No files to remove.
```

Cron schedules still plan to run  interleaved every 30 minutes, will check in on that next week
</blockquote></details>

almost everything in production appears to be working as desired except for an issue with nginx logging.  investigation to be continued


<!-- Sent from Reviewable.io -->

2023-06-20 16:16 UTC, svenevs reviewed
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @BetsyMcPhail)

___
*[`cache_server/remove_old_files.py` line 436 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUe64VT6aRgBxsz2zi_:-NYO_kiG8VCiIQdv6RJh:bn9uuhi) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b732e60161d2a613a6ab34115d39df4fc181f8f1/cache_server/remove_old_files.py#L436)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

almost everything in production appears to be working as desired except for an issue with nginx logging.  investigation to be continued
</blockquote></details>

done, we made it search smaller windows and it works as desired
___
*[`cache_server/rotate_logs.py` line 145 at r5](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NYO_qKJ-QdZOShrQpY-:-NYO_qKKBj3BGmz3Arq3:b9rbc14) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b6573360d80ab5f09752b28d20a932906200e714/cache_server/rotate_logs.py#L145)):*
> ```Python
>         check=True,
>     )
>     log_stdout_stderr(chown_proc)
> ```

fyi this is running in production, we'll be doing a live demo of how it runs for review


<!-- Sent from Reviewable.io -->

2023-06-20 17:13 UTC, svenevs reviewed
> Reviewed 2 of 2 files at r6, all commit messages.
> Dismissed @BetsyMcPhail from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @svenevs)

___
*[`cache_server/health_check.bash` line 116 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NUjCgM93SnDJVCXfl-9:-NYOmgHB10lkKVl87VgH:b-fxctu2) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/950d775c0c6d1a2ca4822420648a28b19ff58c84/cache_server/health_check.bash#L116)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, before this merges / once we are finalized on linux server, I need to re-bootstrap the mac server

sorry for all the noise with the pushing, easiest way to develop this thing is to just work with the live data, but I wanted to also make sure that the README instructions can be copy pasted to make a new one (verify steps for start to finish)
</blockquote></details>

done, mac side is up to speed and running the same things here.  both servers have `/opt/cache_server/drake-ci` symlinked to `/cache/drake-ci` right now.  i will remove that after this PR merges, otherwise the health check jobs (running from `main`) will not be able to find the file to run.


<!-- Sent from Reviewable.io -->

2023-06-20 19:16 UTC, BetsyMcPhail submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-:-NYPEDZq4B7qsl0TVrDA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @svenevs)

___
*[`cache_server/rotate_logs.py` line 11 at r7](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NYPE-vQ9VCTUONy7dB9:-NYPE-vQ9VCTUONy7dBA:b-1i9p1q) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/8c711307220b4659c908885c24ed2db272c21ef8/cache_server/rotate_logs.py#L11)):*
> ```Python
> be corrected.
> 
> 1. The ``nginx`` logging files ``/opt/cache_server/nginx/{access,error}.log`` may have
> ```

FYI Are these comments still true when using the reopen option?


<!-- Sent from Reviewable.io -->

2023-06-20 19:26 UTC, svenevs reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @svenevs)

___
*[`cache_server/rotate_logs.py` line 11 at r7](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-NYPE-vQ9VCTUONy7dB9:-NYPGNw97ZVyWKjlOfzu:b-57fzqx) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/8c711307220b4659c908885c24ed2db272c21ef8/cache_server/rotate_logs.py#L11)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

FYI Are these comments still true when using the reopen option?
</blockquote></details>

done, good call, section was unclear and now reworded


<!-- Sent from Reviewable.io -->

2023-06-20 19:27 UTC, BetsyMcPhail approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @svenevs)



<!-- Sent from Reviewable.io -->

2023-06-20 19:28 UTC, BetsyMcPhail approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/222#-:-NYPGoqD2WLmCTaOe2WW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @svenevs)



<!-- Sent from Reviewable.io -->

2023-06-20 19:28 UTC, merged